### ISSUE TITLE
install directxtk 21.11.0 .. failed

### ISSUE THREAD

**Issue by remyvanlis** [tiltedphoques/TiltedEvolution#223]
While compiling or building the sourcecode on a server (no dedicated GPU present, a 40c/100G proxmox windows server vm) xmake sadly fails to install directxtk. Is there anything that can be done about it? I would really like to run the project on an actual server rather than my pc.

```
please input: y (y/n/m)
y
  => install directxtk 21.11.0 .. failed

cmake not found!
if you want to get more verbose errors, please see:
  -> C:\Users\Administrator\AppData\Local\.xmake\cache\packages\2207\d\directxtk\21.11.0\installdir.failed\logs\install.txt
error: install failed!

C:\TiltedEvolution>
```

![image](https://user-images.githubusercontent.com/62595579/178046812-dafbbfc8-d888-4ba4-a915-690f2e4b026c.png)

**Comment by RobbeBryssinck** [comment]
In the visual studio installer, you need to select the components "Desktop development with C++" and "Game development with C++". Once you've installed those, restart your terminal, and run it again. I will change the build guide to reflect this.

**Comment by remyvanlis** [comment]
You're right, I didn't install the Game development part, just c++. Works like a charm, currently playing together with my housemate. awesome! thanks so much, amazing work <3
