### ISSUE TITLE
Allow changing anchor corner for party info

### ISSUE THREAD

**Issue by ejektaflex** [tiltedphoques/TiltedEvolution#224]
A nice enhancement to have would be for the Setting > Party menu to let the player select which corner of the screen they'd like the party health bars to show up on. Using any interface (SkyUI for example) will cause the party health bars to render on top of it, but another corner such as the top right corner rarely gets many distracting interface elements.

**Comment by Dragonisser** [comment]
https://github.com/tiltedphoques/TiltedEvolution/pull/264
