### ISSUE TITLE
Targeted channeled healing spells do not sync.

### ISSUE THREAD

**Issue by legendaryoaks** [tiltedphoques/TiltedEvolution#225]
Targeted channeled healing spells do not sync.

Spells affected: Healing Hands 

I think that's it but there could be others.

To Reproduce: 
1. Have another player take damage.
2. Attempt to heal the player with healing hands.

What's Expected:
The player will get healed.

The Result:
The player is not healed.

Plugins Used:
```
  0  0     Skyrim.esm
  1  1     Update.esm
  2  2     Dawnguard.esm
  3  3     HearthFires.esm
  4  4     Dragonborn.esm
  5  5     ccBGSSSE001-Fish.esm
254 FE   0 ccQDRSSE001-SurvivalMode.esl
254 FE   1 ccBGSSSE037-Curios.esl
  6  6     ccBGSSSE025-AdvDSGS.esm
  7  7     Unofficial Skyrim Special Edition Patch.esp
254 FE   2 Skyrim Project Optimization - Full ESL Version.esm
  8  8     BSAssets.esm
  9  9     BSHeartland.esm
 10  a     BS_DLC_patch.esp
 11  b     HammetDungeon01.esm
254 FE   3 BSHeartland - Meshes.esp
254 FE   4 TrueHUD.esl
 12  c     SkyUI_SE.esp
 13  d     RaceMenu.esp
 14  e     RaceMenuPlugin.esp
 15  f     iHUD.esp
254 FE   5 dD-No Spinning Death Animation.esp
 16 10     Hothtrooper44_ArmorCompilation.esp
 17 11     SimplyBiggerTreesSE.esp
 18 12     Cloaks.esp
 19 13     Cloaks - Dawnguard.esp
 20 14     Cloaks - USSEP Patch.esp
 21 15     Equippable Tomes.esp
 22 16     PaladinArtifactsAndArmor.esp
 23 17     widescreen_skyui_fix.esp
 24 18     AbandonedPrisonTweaks.esp
 25 19     Apocalypse - Magic of Skyrim.esp
 26 1a     Immersive Weapons.esp
 27 1b     Hothtrooper44_Armor_Ecksstra.esp
 28 1c     KS Hairdo's.esp
254 FE   6 MCMHelper.esp
 29 1d     SkyHUD.esp
 30 1e     Vokrii - Minimalistic Perks of Skyrim.esp
 31 1f     Apocalypse - Vokrii Compatibility Patch.esp
 32 20     Alternate Start - Live Another Life.esp
```

**Comment by Dragonisser** [comment]
https://wiki.tiltedphoques.com/tilted-online/general-information/faq#q-can-i-use-other-mods-with-this-mod

A: our official stance is that, for the best, most stable experience, you should not install other mods. You still absolutely can, and our mod also automatically loads SKSE if you have it installed, but we cannot make any guarantees that these mods won't cause stability issues, play nice with our systems, or that their features will sync. This is up to your discretion. We consider Creation Club mods to fall under this same category, including the Anniversary Upgrade mod pack.

**Comment by ninjanomnom** [comment]
This isn't an issue with other mods as it happens even with nothing but skse, skyrim together, and the address library.

At first I thought it was the disabled pvp making it so even healing hands couldn't affect other players but even with pvp enabled and demonstrably being able to damage other player you can't heal other players with healing hands.

**Comment by ejektaflex** [comment]
I can confirm that even Healing Hands does not work - I was not able to heal anybody with even vanilla magic.

**Comment by ejektaflex** [comment]
Heal Other also does not work (at least on players). I have no tried Necromantic Healing on a player vampire, but something tells me that it wouldn't work if the others do not work either.

**Comment by Dragonisser** [comment]
> This isn't an issue with other mods as it happens even with nothing but skse, skyrim together, and the address library.
> 
> At first I thought it was the disabled pvp making it so even healing hands couldn't affect other players but even with pvp enabled and demonstrably being able to damage other player you can't heal other players with healing hands.

And yet you use SKSE? Its not required.

**Comment by ejektaflex** [comment]
My tests were without SKSE, nothing but Address Library and Skyrim Together.
