### ISSUE TITLE
droped / pickedup items do not sync

### ISSUE THREAD

**Issue by KoromaruKoruko** [tiltedphoques/TiltedEvolution#229]
We managed to duplicate items between each other as one would drop an item and both people could pick it up. 

IE
Sometimes droping is synced but pickups arn't
Sometimes when you drop an item it shows up for the other player but not for yourself.

**Comment by croscas** [comment]
Note that picking up items is not synced as of the FAQ: https://wiki.tiltedphoques.com/tilted-online/general-information/features#inventories-and-equipment

**Comment by KoromaruKoruko** [comment]
"Picking up items is not always synced."

Yes, but knowing when and when not would be a good thing.
that and this issue is more of a tracking issue, so people can report when it is working and when it isn't

**Comment by Dragonisser** [comment]
There you go https://wiki.tiltedphoques.com/tilted-online/general-information/features#inventories-and-equipment

**Comment by Dragonisser** [comment]
There you go https://wiki.tiltedphoques.com/tilted-online/general-information/features#inventories-and-equipment

**Comment by croscas** [comment]
For the record the change in the Wiki is that now it says:

> Dropping items on the ground is synced, someone else picking it up isn't synced.
> Only pre-placed items in the world by Bethesda/Mod creator (eg. an item in a dungeon), are synced when picking those up.
