### ISSUE TITLE
Bug: Unable to close Connection UI for Proton/Linux

### ISSUE THREAD

**Issue by ArcadeDan** [tiltedphoques/TiltedEvolution#232]
Fresh install and installed SkyrimTogether under accordance to this https://www.youtube.com/watch?v=7ogIhWUxPyE
Connection UI will break movement animations and will pop up pressing either F2/R_CTRL

issue #231 refers to my issues as well

**Comment by ArcadeDan** [comment]
So for those struggling, I found a temporary solution. pressing F2/RightCTRL and pressing escape immediately after allows you to pause and you may press the hotkey again to hide it. press escape again and you can move again.

**Comment by arazadaz** [comment]
You can also spam F2 until it decides to close. I just press and hold the button for a second and release until it works. There's a Pull Request that's been merged already to add an escape feature, so I'd consider this closed.

**Comment by Dragonisser** [comment]
Should work with this fix https://github.com/tiltedphoques/TiltedEvolution/pull/231
Wait for 1.1 (today)
