### ISSUE TITLE
Enemy loot getting multiplied

### ISSUE THREAD

**Issue by ninjanomnom** [tiltedphoques/TiltedEvolution#233]
Sometimes when killing enemies their death drops are much more than expected, hundreds of skeever tails from a single skeever for example. This doesn't seem to affect loot which was in their inventory before death like equipment on humans, just things which get added on death of the mob.

From what it looks like, sometimes enemies will fail to die on hitting 0 hp for a bit and the more damage you do to them while they're in this state the more they drop. This also seems to scale inversely with the hp of the enemies, as in the lower health an enemy has the easier it is to do more damage and cause more drops.

**Comment by Thercious** [comment]
Can confirm. A friend playing on my server was able to get 33k wolf pelts out of a single dead animal, the numbers seem to increase absurdely fast when striking the enemy with a continuous spell, such as **Flames**.

**Comment by JazzyScuffs** [comment]
Can also confirm. We were able to loot 26 wolf pelts from a single ice wolf

**Comment by rlberry** [comment]
251 wolf pelts for me!
