### ISSUE TITLE
No Cyrillic in chat/text fields

### ISSUE THREAD

**Issue by Sidiusz** [tiltedphoques/TiltedEvolution#234]
Will Cyrillic be added to the project?

**Comment by croscas** [comment]
Could you provide more context regarding what is exactly missing?

**Comment by kulcris** [comment]
I believe he is referring to Cyrillic letters missing from the game 
абвгдеёжзийклмнопрстуфхцчшщъыьэюя

These letters are used in these languages 
Belarusian, Bulgarian, Kazakh, Kyrgyz, Macedonian, Montenegrin, Russian, Serbian, Tajik (a dialect of Persian), Turkmen, Ukrainian, and Uzbek

So when a user has the game set to Russian for example. and they choose a dialogue choice or type in chat.  it it causes missing letters in the chat box

**Comment by Dragonisser** [comment]
> I believe he is referring to Cyrillic letters missing from the game абвгдеёжзийклмнопрстуфхцчшщъыьэюя
> 
> These letters are used in these languages Belarusian, Bulgarian, Kazakh, Kyrgyz, Macedonian, Montenegrin, Russian, Serbian, Tajik (a dialect of Persian), Turkmen, Ukrainian, and Uzbek
> 
> So when a user has the game set to Russian for example. and they choose a dialogue choice or type in chat. it it causes missing letters in the chat box

The chat supports all kind of characters, even Chinese, Japanese, Emoji. I doubt it has anything to do with writing in Cyrillic in chat.

**Comment by croscas** [comment]
@kulcris Thank you for the clarification. Still it would be very useful if someone could provide an screenshot showing the problem in the dialogues or the chat.

**Comment by Dragonisser** [comment]
> @kulcris Thank you for the clarification. Still it would be very useful if someone could provide an screenshot showing the problem in the dialogues or the chat.

Well "someone" is the creator of this issue. @Sidiusz

**Comment by Sidiusz** [comment]
>  I doubt it has anything to do with writing in Cyrillic in chat
:|

![Screenshot_1](https://user-images.githubusercontent.com/20544939/178481813-4784b513-a63f-4ec7-b116-87f8174cb7a3.png)

**Comment by Dragonisser** [comment]
Works perfectly fine

![image](https://user-images.githubusercontent.com/4233773/178486873-781f2112-93a0-4bf9-bd3b-e4605bb66d7a.png)

**Comment by Dragonisser** [comment]
Apparently the problem only happens when its typed into the chat, copying works fine.
