### ISSUE TITLE
Unable to set hotkeys while connected to a server

### ISSUE THREAD

**Issue by sheph1220** [tiltedphoques/TiltedEvolution#235]
You are unable to press 1,2,3... etc on your favorites menu to bind your hotkeys while your favorites menu is open and you are connected to the server. Pressing 1,2,3... etc, just activates that hotkey as if the menu were not open instead. I suspect it is because the game is not paused as it normally would be. The current workaround is to disconnect momentarily every time you get a new spell or item you want to hotkey and reconnect to the server, where the hotkeys will at least be usable once bound.

I tested this with the bare minimum mods installed: only Address library for SKSE. I uninstalled SKSE prior to testing. I also tested Skyrim Souls RE offline and it was able to allow hotkeys to be bound with the favorites menu while unpaused, but it conflicts with this mod, so that is not an option either.

**Comment by Vermunds** [comment]
This is fixed by Skyrim Souls RE here:
https://github.com/Vermunds/SkyrimSoulsRE/blob/master/src/Menus/FavoritesMenuEx.cpp#L42

**Comment by Pao-Lumu** [comment]
+1
Also happening for myself and friends.

**Comment by Dragonisser** [comment]
https://github.com/tiltedphoques/TiltedEvolution/pull/302
