### ISSUE TITLE
Interface loading inconsistently

### ISSUE THREAD

**Issue by Thercious** [tiltedphoques/TiltedEvolution#244]
The interface doesn't load properly sometimes, showing only the cursor when pressing R-CTRL or F2, with nothing else to interact.
I've seen it happen intermittently, experiencing this issue first-hand a couple of times, as well with other players.

I found that a palliative solution is closing and reopening the game until it loads properly, so that the chat and buttons are visible and interactible again.

**Comment by KoromaruKoruko** [comment]
i've only experienced this 3 times so far, but it seems to happen like 2-3 times before working again for my friend.

**Comment by kulcris** [comment]
This is related to SKSE, if you do not have SKSE installed it does not happen

**Comment by jjnether** [comment]
Please do not submit bug reports here, this is meant only for developers. Rather, your reports should be directed [here](https://github.com/tiltedphoques/bug-feature-reports). Please view the [troubleshooting](https://wiki.tiltedphoques.com/tilted-online/guides/troubleshooting/gameplay-issues#ui-not-showing) before submitting a bug report. This issue has been noted. #257

**Comment by Dragonisser** [comment]
In favour of this issue (https://github.com/tiltedphoques/TiltedEvolution/issues/257), ill close this one here for now.
