### ISSUE TITLE
invincble enemies

### ISSUE THREAD

**Issue by DannyDarth** [tiltedphoques/TiltedEvolution#250]
occasionally enemies dont seem to take damage or die.

**Comment by Pingu-Pox** [comment]
This is addressed in their wiki, try this mod in your loadorder.
No Killmoves - No Killcams - No Killbites SE
https://www.nexusmods.com/skyrimspecialedition/mods/13395

**Comment by RobbeBryssinck** [comment]
Duplicate of #211
