### ISSUE TITLE
UI not always showing when pressing F2/RCTRL

### ISSUE THREAD

**Issue by Dragonisser** [tiltedphoques/TiltedEvolution#257]
There are plenty of occasions where pressing either of the 2 keys to activate the UI, nothing happens. This isn't just a one time issue, but cant be fixed without quitting the game or with luck exiting to the main menu.

Debugging the issue showed that even though the UI receives the callback to activate it, setting the BehaviourSubject to TRUE, the UI wont change and the BehaviourSubject is still set to FALSE when logging it.

Most likely some false usage of Angular or legacy spaghetti code.

https://github.com/tiltedphoques/TiltedEvolution/blob/master/Code/skyrim_ui/src/app/services/client.service.ts#L128=

https://github.com/tiltedphoques/TiltedEvolution/blob/master/Code/skyrim_ui/src/app/components/root/root.component.ts#L87=

https://github.com/tiltedphoques/TiltedEvolution/blob/master/Code/skyrim_ui/src/app/components/root/root.component.html#L14=

More information will come...

**Comment by scomans** [comment]
My changes might already fix this problem. Haven't had it since 🤔

**Comment by DenisNovac** [comment]
I had a crash and after that menu doesn't open anymore. Can i submit some logs?

**Comment by BlueAmulet** [comment]
Still having this issue with 1.1.0, hasn't happened for me but 3 out of 3 launches for my friend the UI refused to open.

**Comment by Dragonisser** [comment]
> Still having this issue with 1.1.0, hasn't happened for me but 3 out of 3 launches for my friend the UI refused to open. Verified that the F3 screen said 1.1.0

There are more fixes in the making.

**Comment by FastGecko5** [comment]
Seems to be a conflict with Steam Overlay. Disabling Steam Overlay fixed it for me.

**Comment by Sturlen** [comment]
Doesn't appear to be an issue with Angular, as you can still connect a debugger and run js commands in the console. Issue seems to be happening between listening for the F2 key and sending the Activate event to the UI.

**Comment by Dragonisser** [comment]
> Doesn't appear to be an issue with Angular, as you can still connect a debugger and run js commands in the console. Issue seems to be happening between listening for the F2 key and sending the Activate event to the UI.

At least in the past, angular received everything fine but completely ignored it and no updates were triggered.
