### ISSUE TITLE
UI serverlist improvements

### ISSUE THREAD

**Issue by Dragonisser** [tiltedphoques/TiltedEvolution#260]
- [ ] Widen serverlist for future implementation of more data (tags, description, etc)
- [ ] Hide (or barely visible) chat/general menu when opening the serverlist -> mockup below (worth a shot for other menus)
- [ ] lazy loading for serverlist -> no need to display 1500 server
- [ ] Default sort by favorite and then player count

![image](https://user-images.githubusercontent.com/4233773/178366735-9e362ea2-72ae-43bf-881d-eb09d9c6d9a8.png)

**Comment by MaverickMartyn** [comment]
Maybe a way to add the current server, or just manually add entries to favorites.
Would be nice if you have a private server, since at this time you have to retype the adress and password.

On a side note. This is awesome. Thank you so much. :)

**Comment by Dragonisser** [comment]
> Maybe a way to add the current server, or just manually add entries to favorites. Would be nice if you have a private server, since at this time you have to retype the adress and password.
> 
> On a side note. This is awesome. Thank you so much. :)

Saving the last manual connected server has been done already, its just not live yet.
https://github.com/tiltedphoques/TiltedEvolution/pull/246

Besides that, having password protected servers in the serverlist again will be done in a different PR, which should feature something like saving a password for favorited server, so you just have to press "Join" if the password is saved.

https://github.com/tiltedphoques/TiltedEvolution/pull/227

**Comment by scomans** [comment]
1. no problem
2. no problem
3. is loading them or showing them the problem?
4. currently you can only sort by one criteria. So that must be changed to support multiple.

**Comment by Dragonisser** [comment]
Fixed https://github.com/tiltedphoques/TiltedEvolution/pull/278
