### ISSUE TITLE
Unable to launch Skyrim Together

### ISSUE THREAD

**Issue by DarkWalf88** [tiltedphoques/TiltedEvolution#268]
Me and my friend have bought the game and we are trying to play together, we installed both Skse64 and All in one (anniversary edition). We downloaded the mod via Vortex, linked vortex to skyrimSE.exe, installed the mod and the library, created a new tool in the dashboard to start modded skyrim via Vortex and started the server on my PC. I am able to run the game properly and joining the server, but my friend is unable to even run the mod in singleplayer, in fact he linked the Skyrim Together with the SkyrimSE.exe, but when he launch the game from the Vortex client or directly from the foulder it doesn't start. He doesn't get any error message nor crash report, the vortex goes in to running for a few seconds, then nothing appens even if we wait half an hour. Same goes if he run it as administrarot. I'm realy going crazy trying to fix it myself, he tryied reinstalling mod, reinstalling SKse64 (the versin is correct because we both can run it), he also tryied to re-link the Skyrim together via <Spacebar+double left-click> and we didn't managed to fix it. So I ask u for an help fixing this.

**Comment by PyThLeeK** [comment]
I have the same problem, still no solution. However, i found out some small, probably unimportant bits.

No TiltedPhoques in registry (probably unimportant)

Event loger shows there's either Exception code: 0xc0000005 or 0xc000041d with COMDLG32.dll every time I launch the SkyrimTogether.exe

**Comment by DarkWalf88** [comment]
I my case, we have the same things, the only difference between me and my friend is the hardware, i have a razen 5 an he has an i3, maibe the mod give problem with this (cpu isn't enouth powerful to run the mod, but i don't think so because we play modded minecraft togheter and there are no errors) and the other thing is the difference in RAM, but i think 14 Gb ram are enought. I shoul ask him to see the event log to know if he has your same errors but for now i think we should wait and hope

**Comment by PyThLeeK** [comment]
I also have ryzen 5, so it probably won't be caused by CPU, but as you said, we shall wait and we shall hope.

**Comment by jjnether** [comment]
Please do not submit bug reports here, this is meant only for developers. Rather, your reports should be directed [here](https://github.com/tiltedphoques/bug-feature-reports). Concerning your issue, it may be the issue discussed [here](https://wiki.tiltedphoques.com/tilted-online/guides/troubleshooting/gameplay-issues#crashing-on-connect-aes-ni), but otherwise hardware shouldn't be an issue. Your friend can easily test this if he just tries to play the game without Skyrim Together Reborn installed.

**Comment by DarkWalf88** [comment]
Sorry, I'll keep that in mind for the future

**Comment by kingoffishes331** [comment]
I am also having this exact issue actually and I am frankly not tech savvy enough to really know what could be going on. The links above don't seem to go anywhere anymore.

**Comment by Dragonisser** [comment]
Stale issue. Closing for now.
