### ISSUE TITLE
Not a bug but a question; is this compatable with existing skyrim AE mods? 

### ISSUE THREAD

**Issue by Xanthus58** [tiltedphoques/TiltedEvolution#272]
So i only just heard about this project by a friend and were seriously debating on setting it up. But we both like to have tons; i mean like 300+ mods all for skyrim AE i was wondering if this would be compatible with mods; and creation club content. Or if it'd need to be an entirely vanilla experience to work properly; similar to how other multiplayer extensions need vanilla like the sims

**Comment by jjnether** [comment]
Please reference the [wiki](https://wiki.tiltedphoques.com/tilted-online/) and its FAQ page first, then ask any questions in the discord (find link on [official website](https://skyrim-together.com/) )

**Comment by Xanthus58** [comment]
My apologies i was unaware of the wiki; i found this project via github and the wiki provided in github did not seem to work. @jjnether

**Comment by jjnether** [comment]
@Xanthus58 No problem, were there broken links? Or they just didn't take you to the webpage you expected?

**Comment by Xanthus58** [comment]
@jjnether whenever i clicked the wiki button in the project page 
![image](https://user-images.githubusercontent.com/66909997/178578705-d2a81fb2-d301-4d5e-851c-b5794b72958e.png)

Which normally redirects to a github internal wiki system; heres an example of a functional one (small one i made for a project of mine)
![image](https://user-images.githubusercontent.com/66909997/178578854-76811fae-991c-4dbd-9ec0-1f94c8d31103.png)

I just redirectes me to the codebase for the project. Instead of an internal or external wiki system.

**Comment by jjnether** [comment]
That setting just happens to be left on in all the repositories for this project, it doesn't lead anywhere

**Comment by Xanthus58** [comment]
I believe that would be a good idea and avoid future confusion for members like myself; who typically operate almost entirely within GitHubs ecosystem.
