### ISSUE TITLE
Feature Request: Markers for Party Members

### ISSUE THREAD

**Issue by Rafaelbgf** [tiltedphoques/TiltedEvolution#284]
First of all, thank you all for this creation.

I have a quick suggestion, to have some sort of marker showing the location of party members, maybe as a quest.

I'm planning to play this with my wife, she's new to this game and I'm sure we're going to get lost sometimes so finding each other would be nice.

**Comment by theboee** [comment]
Already in the works

https://github.com/tiltedphoques/TiltedEvolution/pull/202

**Comment by Dragonisser** [comment]
Use the template
