### ISSUE TITLE
(BUG)Diplomatic Immunity, Only Hosts Items Appear In Delphine's Chest

### ISSUE THREAD

**Issue by theboee** [tiltedphoques/TiltedEvolution#285]
## Description

In the main quest Diplomatic Immunity, players are told to speak with Malborn about sneaking in some supplies to the thalmor embassy. Only the host can talk with Malborn and give him supplies. (Not sure if there would be a way for everyone to give him supplies). Once completed you are then instructed to talk with Delphine to actually go to the event. Before sending you off she gives you some "Party attire", which is given only to the host. She then takes all of your inventory items and places them in her secret basement chest. Once completed you are supposed to collect your belongings from said chest. Only the hosts items are stored in the chest, connected players items are deleted the moment the host steps on the carriage to the party.

## Steps to reproduce

1. Start the game.
2. Connect to the server.
3. Play through Diplomatic Immunity with 2 or more players in a party
4. Finish quest
5. Go to Delphine's lair
6. Find only host's inventory items in chest

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

To find every party members items in the chest

**Comment by ejektaflex** [comment]
It sounds like we may want to disable sync for that specific chest? That might be the easiest way to fix it.

**Comment by RobbeBryssinck** [comment]
Fixed in 1.1.
