### ISSUE TITLE
(BUG)Game Crashes when attempting to catch new player up to host

### ISSUE THREAD

**Issue by theboee** [tiltedphoques/TiltedEvolution#287]
## Description

I joined a friend as a new character as he was going through the quest, The Horn of Jurgen Windcaller. Towards the end of the dudgeon the game attempted to sync my character. Catching me up on already completed quests and giving me shouts I should of learned already. Half way through this process the game crashed losing all of the progress made. It didn't attempt to sync again.

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Start the game.
2. Make new character
3. Escape Helgen
4. Join Friend during his playthrough of any quest
5. Have friend complete a part of said quest
6. Game attempts to catch player up to host
7. Game Crashes part of the way through

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [x] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

For it to sync without crashing

**Comment by Dragonisser** [comment]
https://wiki.tiltedphoques.com/tilted-online/general-information/playguide#guidelines
