### ISSUE TITLE
Is this a Sync issue?  Need help.

### ISSUE THREAD

**Issue by Jamellian** [tiltedphoques/TiltedEvolution#288]
Mods installed:
USSEP for Ver 1.6.353
Address Library for SKSE all in one AE
Skyrim together Reborn

The issue I have is very similiar to the one found here:
https://www.reddit.com/r/SkyrimTogether/comments/j8wwtn/enchanted_items_not_synced_what_does_this_mean/

The issue being that everything I enchant, once I interact with it (inventory), the game crashes.
No dropping, no selling, or trading.
  
Crafting is a huge part of my game life, please help me find a solution.

# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

## Description

A clear and concise description of what the bug is, Include any formIDs relevant for us to use ie,

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Start the game.
2. Load a saved game where your character is in Whiterun standing inside your house.
3. Connect to the server.
4. Exit your house.
5. Quickly turn around and re-enter your house as soon as you are outside
6. Game crashes

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"

## Evidence (optional)

Show us what happened.

**Comment by Dragonisser** [comment]
You didnt follow the template at all.
