### ISSUE TITLE
food

### ISSUE THREAD

**Issue by holyaurora21** [tiltedphoques/TiltedEvolution#290]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

## Description

using playtogether.gg  server and party members are constantly hungry, eating food does not make a difference. (host does not get this issue)
any way to solve this?

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

use a playtogether server and make a party (did not get this issue till we joined into a party)

## Reproduction rate
Not sure if it will keep happening, need to try again

## Expected result

party members to not be hungry?

## Evidence (optional)

Show us what happened.

**Comment by Dragonisser** [comment]
AE content is not supported

**Comment by Dragonisser** [comment]
Youre using the mod Survival.

**Comment by holyaurora21** [comment]
![image](https://user-images.githubusercontent.com/64653103/178843879-cf278e8f-88c5-4ea6-b9a8-5376b3c17f12.png)

how do i turn off the mode? or do we need new characters?
