### ISSUE TITLE
Conjuration summons are always flagged as hostile  

### ISSUE THREAD

**Issue by BaloneyChops** [tiltedphoques/TiltedEvolution#294]
## Description

A Conjuration summon that was casted by a player in a group would be seen as hostile by other party members or passive/friendly NPCS. If a player Summons an allied entity, that allied entity is always known as hostile from another players perspective in the group. All of the NPCS in a town would start attacking a players summon because the summoned entity is flagged as hostile all the time for no reason.

## Steps to reproduce

1. Start the game
2. Start new game
3. Finish Helgen sequence 
4. Join a party CO-OP
5. Obtain spellbook of any conjuration summon 
6. Be in a city with CO-OP group 
7. Cast conjuration summon 
8. All party members will see casters summon as hostile 
9. All NPCS will now randomly start attacking casters summon randomly 

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [*] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

I expected a players casted conjuration summon to be friendly to the party group and passive/friendly NPCS.

**Comment by kulcris** [comment]
I wonder if adding the player to the player faction will fix this

**Comment by Sturlen** [comment]
I've done some digging with the debugger and I can't find any values in TESNPC or Actor that indicatess if an NPC is a summon or found naturally. Summoned creatures do not appear to have any special faction or relationships, other than what the base creature has. This means that your local summon will be replicated to remote players as if it was spawned by the console, meaning it will be hostile.

The above appiles to raised corpes too.

If someone could RE this "summon flag" and inlcude it in the TESNPC, then it should be easy to make summoned creatures friendly for remote players.

*Tested using a breakpoint in `bool TP_MAKE_THISCALL(HookSpawnActorInWorld, Actor)`
https://github.com/tiltedphoques/TiltedEvolution/tree/dev/Code/client/Games/Skyrim/Actor.cpp#L582*

**Comment by RobbeBryssinck** [comment]
Unlikely that the TESNPC contains the summon flag, since the conjured actors share the same TESNPC base with non summoned actors of that type. The flag is most likely in Actor or in AIProcess.

**Comment by RobbeBryssinck** [comment]
https://github.com/Ryan-rsm-McKenzie/CommonLibSSE/blob/master/include/RE/A/Actor.h#L202

IsCommandedActor is set on summons. There must be some kind of owner handle attached to the actor too.

**Comment by Sturlen** [comment]
> IsCommandedActor is set on summons

Seems like I've been searching for the wrong variable name up til now. Also thank you for the link, it's been quite useful in understanding Skyrim's internals.

Further testing with `IsCommandedActor` has turned up that setting the flag on another player's summon will not make it friendly. Still, I think synchonizing this flag would be a step in the right direction for fixing summons.
I've found `kOwnerIsNPC` in AIProcess, which sounds promising. Will have a look later.
