### ISSUE TITLE
(BUG) Random Leveling/Leveling Off Of Party Members

### ISSUE THREAD

**Issue by Djmoss24** [tiltedphoques/TiltedEvolution#295]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

## Description

When playing SkyrimTogether with Party Members I can continually hit them to level up skills as if they were enemies. Also, while party members were performing various actions, in this case healing/sneak attack, One Handed sometimes leveled up for every Party Member.

Related formIDs|
---------------|

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Start the game
2. Launch SkryimTogether Console Window
3. Connect to the server
4. Join a party
5. Melee/Cast Spells on Party Members
6. Can continue leveling like normal
7. Sometimes OneHanded would level up

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [y] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

With PvP disabled, I just expected to be able to hit party members but not gain xp off of them nor have OneHanded randomly level up.

## Evidence (optional)

Show us what happened.

**Comment by GoodOldJack12** [comment]
XP Sync is an intended feature (see https://github.com/tiltedphoques/TiltedEvolution/pull/265), but I have also observed entirely _random_ skills being leveled. As in, I was playing healer, my party was all melee, and I randomly got destruction experience as they were doing things.

**Comment by Djmoss24** [comment]
Thank you for the info about xp sync. I did not realize that. We were playing around a bit longer after I made the initial post. I did notice when a random skill leveled it was usually the last skill used. For example when I was attacking with a one handed weapon, randomly the party members would receive a level in one handed even though one was healing and the other using a bow. Vice versa as well. I was attaching and randomly received a level in restoration lol.

**Comment by kulcris** [comment]
For the purpose of this explanation
Local player = the player who is playing the character on their screen 
this part of the code goes off of the local player's last used skill. it really shouldn't be effected by the skill the other player was using, unless the game is assuming the report player is the local player and setting last used skill to whatever they are using. 

Any mods installed?

**Comment by Djmoss24** [comment]
We were playing on the Anniversary Edition with no other mods besides SkyrimTogether and plug-in requires for it. Unsure if that answers the question well.

**Comment by GoodOldJack12** [comment]
So if I understand correctly, it's intended that when the party recieves xp, they receive it according to the last used skill? That may have been consistent with what I've been seeing at least.

**Comment by Djmoss24** [comment]
Correct.
