### ISSUE TITLE
Game keeps crashing at start, nothing helps

### ISSUE THREAD

**Issue by Hajatu** [tiltedphoques/TiltedEvolution#297]
### Hello, after trying to run Together Reborn several times over I'm stuck with crash during loading screen. Around the time when the Steam Overlay popup should disappear the game crashes smoothly without any error prompt.  
___
I tried:
* both Vortex and MO2 (both with and without "-r" command)
* checked with CPU-Z that my i5-8300H supports and has AES protocols
* running everything as admin 
* running game with Steam Overlay option unchecked
* verifying files multiple times (always went fine)
* forcing my GTX1050 usage on both SSE and ST .exe files
* reinstalling game
* clearing .ini files in My Games directory
* updating my distributables and GPU drivers

The game on its own works perfectly fine, as well as SKSE version of it. I went through both tutorials step by step, always ending up with the same result. Game is up to date (1.6.353.0), and I don't have citrix workstation on my computer (as it apparently causes some troubles).

### I don't have and never did any gameplay mods.
___
As attachments I'm sending logs from ST, Crash Logger, and SKSE:
[cef_debug.log](https://github.com/tiltedphoques/TiltedEvolution/files/9109369/cef_debug.log)
[tp_client.log](https://github.com/tiltedphoques/TiltedEvolution/files/9109370/tp_client.log)
[CrashLogger.log](https://github.com/tiltedphoques/TiltedEvolution/files/9109367/CrashLogger.log)
[skse64.log](https://github.com/tiltedphoques/TiltedEvolution/files/9109368/skse64.log)

**Comment by kulcris** [comment]
A few more debugging steps you can try. 

Does this still happen with latest version
You say you have no mods but SKSE is not required, try with only STR and the Address library for AE(Address library says it requires SKSE but that is not true in this case)
Make sure all recording software is disabled (NVidia overlay, fraps, etc.)
Make sure any antivirus software is not flagging any of the STR files

When you say it crashes when the "steam overlay" is supposed to go away. Is this while you are loading a save? or is it just a few seconds after you get to the main menu.

**Comment by Hajatu** [comment]
Game doesn't even show me main menu it crashes on a loading screen with medallion, after launching it, around the time when the Steam Overlay prompt goes away (so like 3-4 seconds).
___
I did all of it again using Vortex, this time only installing Address library and STR. Also I uninstalled OBS Studio which I had on my computer, closed GEForce Experience, checked for antivirus flagging STR files (none was flagged) and it again crashed on start. On screen there was single dragon medallion, loading circle in the bottom right corner did couple spins, froze for a brief second and I got back to Dekstop. This time though, I was not prompted to pick a Skyrim.exe file, so I ran it one more time with "-r" command. This time I've got a black screen for, like, two seconds, then it jumped to medallion screen and did everything as usual, crashing after few seconds of loading screen.

**Comment by Dragonisser** [comment]
Backup your saves and delete the Skyrim Special Edition folder in Documents/My Games

**Comment by drkinkykinkles** [comment]
Have you launched the game at least once from Steam on its own? I noticed I was getting an immediate crash to desktop before the game reached the main menu after downloading the game and going through the mod setup.

It turns out I needed to launch the game regularly from Steam once so that the game could do whatever first-time setup it needed to do, then I could launch the game modded with the Together Reborn mod just fine.

**Comment by Hajatu** [comment]
Yes, after re-downloads, re-installs, and clearing game documents in My Games folder, I always launched the game once.

**Comment by reveriadive** [comment]
I'm having a crash on startup as well. Have confirmed that AES is enabled. Skyrim runs fine by itself.
[cef_debug](https://pastebin.com/raw/FSQWBGmy)

**Comment by SpaceyyyBoyo** [comment]
Having this issue, have been attempting to find solutions for about 6-8 hours. No solution online, have disabled all mods and disabled SKSE, still doesn't work. We are running on STR 1.5.0. Launching from Mod Organizer, running the game vanilla and on SKSE works fine, it only crashes on Skyrim Together Reborn.
