### ISSUE TITLE
Certain NPC's only visible to some players

### ISSUE THREAD

**Issue by Alex-Merrill** [tiltedphoques/TiltedEvolution#298]
## Description

One player in a three person party had an assassin target them. The other two players in the party could not see this assassin, nor was the assassin attacking them. (I used a fire spell casted in the direction the other party member was fighting in, and I seemed to get XP from it, however I'm not sure if that came from hitting another party member or from hitting the assassin). Furthermore, this issue happened a quite a few times to each member of the party. We would all be walking down a road for example and one person would see an NPC or a group of NPCs but no one else could see them.

I tried looking through issues to find if this has been reported and couldn't find anything, sorry if this is a duplicate.

## Steps to reproduce

1. Start the game.
2. Join a party with at least 2 people (We were playing with 3, not sure if this matters)
3. Walk around roads where random NPCs can spawn.
4. Wait until it happens?

Sorry I can't get more detailed than this, seems to happen randomly with NPC spawns, so not sure how to consistently reproduce it without it talking a long time.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Not having NPCs visible to only certain party members.

**Comment by RobbeBryssinck** [comment]
Fixed in #314
