### ISSUE TITLE
Autowalking bug

### ISSUE THREAD

**Issue by Shook595** [tiltedphoques/TiltedEvolution#299]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

## Description

You can walk around without having to press any buttons (Not Caps lock)

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Start the game.
2. Press W or any movement key like A, S or D and hold.
3. Press ctrl to open the chat while holding the movement key.
4. Release the movement key.
5. Press esc.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [ x ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"

It happened on accident I was just walking around and pressed ctrl.

## Evidence (optional)

Show us what happened.

**Comment by Kiloutre** [comment]
> Yes, Skyrim has an auto walk feature when you press C.

He means that opening the multiplayer UI makes the game unable to detect keys being released, so if you're moving or sprinting it'll keep doing that
