### ISSUE TITLE
Date and Month are bugged out 

### ISSUE THREAD

**Issue by EnoughReality** [tiltedphoques/TiltedEvolution#305]
The date and month are currently bugged out in the system/quest menu

How to reproduce
1. Start the game.
2. Open the system menu whether connected to a server or not

Please check just _one_ of the following reproduction rates:

- [✓] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)

Show us what happened.

![Inked20220714115837_1](https://user-images.githubusercontent.com/109303738/179039613-56c94419-0481-4c62-9138-b248c80c1148.jpg)

**Comment by RobbeBryssinck** [comment]
What is the bug exactly?

**Comment by EnoughReality** [comment]
Only the time changes, so when another day comes and goes the date and year remain the same, such as Morndas, 0th of morning star 4E 0

**Comment by DJLegends1011** [comment]
noticed it too wondered wth is it double 0
