### ISSUE TITLE
Issue with damage on Party Leader vs Non Party Leaders

### ISSUE THREAD

**Issue by androbourne** [tiltedphoques/TiltedEvolution#306]
No mods on this test is required. It can be reproduced without mods.

## Description

So I could eyeball the fact as Party Leader I seemed to be taking more damage than the others in my party. At first, I thought this issue was related to how all mobs aggro the party leader by default on patch 1.0. I ignored this for a while until I notice we were fighting one mob and I was taking full damage (40-60s) but when I died, and the mob turned to aggro the rest of the party, they were taking WAY LESS damage. (like 6s-15s). I've since than performed extensive testing and found the issue to be as follows:

As a non-party leader, NPCs in melee will hit you with punch attacks. As a normal player, you can see the NPC pull out its weapon and show the weapon attack animations. But you take punch damage and you can hear the punch effects instead of the weapon hit sound effects. It appears the equip code might be running too early or too late (maybe due to code being executed remotely to non-party leaders) and because so, the NPC don't get the weapon equipped prior to hitting non-party members. However, as the party leader, the code isn't running remotely and it works fine, meaning the party leader takes full damage, while non-party leaders do not.

Still an issue as of patch 1.1.

Related formIDs|
none.

## Steps to reproduce

1. Join a server
2. Created a party
3. Invite a player
4. Have mob attack you as Party Leader (will take normal weapon damage)
5. Die as host or force aggro to non-party leader
6. Watch as NPC aggroed to non-party leader does 6-15s in punching damage

If you die as host and you are near another player. The mob will change to its weapon and attack the non-party leader with full damage from the weapon but, shortly after then switch to punch attacks. If you don't die and just have the non-party leader pull aggro from the mob, it will just switch to punching right off the bat.

## Reproduction rate

It is very easy to reproduce as it happens about 99% of the time. It is only affected by melee. Ranged attacks from bow and magic appear to be working fine for non-party leaders in terms of damage.

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

Describe your expected result i.e. answer the question "What did you expect would happen?"

The expected result is that the NPCs hit non-party members for the same damage they are hitting the party leader for.

## Evidence (optional)

https://youtu.be/xhgxAmtFB0w

**Comment by Humankiin** [comment]
Still experiencing this on latest build (1.4.1). As in the video, I think it has something to do with them constantly switching weapons. Ranged is fine. In melee, however, for non-party leaders, the melee weapons often register as punch attacks, significantly reducing difficulty for everyone aside from the leader.

**Comment by RobbeBryssinck** [comment]
Will be fixed in the next update (1.5.1).

**Comment by SirSmith148** [comment]
This is still not fixed, and the fix that was linked has nothing to do with the problem that was posted
