### ISSUE TITLE
Request for Chest contents synching in dlc/modded homes to be a toggleable feature on servers

### ISSUE THREAD

**Issue by Merik2013** [tiltedphoques/TiltedEvolution#308]
## Description

A toggleable server function for whether or not storage in dlc or modded housing syncs between players.

## Additional context

The 1.1 patch turns this off completely, but this can cause issues with housing that's set to dynamically update depending on what's been placed in storage. This is fundamentally how the storage in Legacy of the Dragonborn functions. If this isn't allowed to sync between players then the features of mods such as this will not sync between players either.

**Comment by ejektaflex** [comment]
I'll look into adding this. Note that after explicitly re-enabling sync on places that were not previously synced, any number of people could lose access to items stored in their chests. As such, it's best to keep it one way or the other for the whole playthrough. :)

**Comment by Merik2013** [comment]
I'll bear that in mind, and thanks for taking a look at it.
