### ISSUE TITLE
Party members Legtimate looting causing 1gold per object viewed bounty to Party Leader

### ISSUE THREAD

**Issue by Blackweaponmastr** [tiltedphoques/TiltedEvolution#309]
# READ IF YOU HAVE MODS
Server + All players are running Skyrim.esm, Update.esm, Dawnguard.esm, HearthFires.esm, Dragonborn.esm (in that order)

## Description

Whenever a party member interacts with a loot able object (book, barrel, chest) the party leader is "fined?" with a 1 gold bounty. Legitimate loot able objects also cause party leader to get a 1 gold bounty per object. The party leader can interact with a chest, receive no bounty and then a party member can interact with the same chest (both in full view of everyone) and the party leader will then receive a 1 gold bounty.  

## Steps to reproduce

Testing was done mostly in Dragonsreach / Bannered Mare / whiterun - Objects such as cub boards, barrels, chests...etc -- once a party member was able to view the contents of the object the party leader would receive a 1 gold bounty. 

Fauna and buckets in Whiterun did not replicate this.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)

## Expected result

Party Leader and Party Members being able to loot and interact with objects 

## Evidence (optional)

Show us what happened.

**Comment by GoodOldJack12** [comment]
It's not just the party leader, from our pov it looked like if someone took something, a -different- person was stopped by a guard and arrested.

**Comment by kulcris** [comment]
I would think all items that are marked steal between players should be the same if you are progressing the same quests (and took the same path through Helgen)

Is this happening on items that normally wouldn't have the possibility of having the stolen flag on it?  (loot in a dungeon for example)

**Comment by GoodOldJack12** [comment]
If I remember correctly, we were in Riverwood trader's and the display items weren't marked "steal" for one person. I'm not aware of a quest that would make those free to take.

**Comment by Lithial** [comment]
This bug is pain. Had my party member stealing around white run/riverwood and It seems like if I was in the loaded cell that I would get a bounty. Also got one for her reading books. Sometimes the steal text came up and sometimes it didn't.

**Comment by GoodOldJack12** [comment]
It looks like reading a book makes you take it from the other players' pov. I've seen someone read a book and then have it disappear on my end.

**Comment by kulcris** [comment]
Might be setting the owner to the first player who picks it up. Then when
another player picks it up they are "stealing" it

The bounty going to the player who didn't pick it up though might be an
activation sync thing and since the local player did not pick it up the
game doesn't know what item it was to calculate bounty cost

**Comment by attckdog** [comment]
my party had the same problem on brand new characters.
We left helgen, went straight to Riverwood,
talked that lady and got her key to take stuff from the house. Party went into the house to loot stuff that wasn't stealing.
Every item my party members picked up added 1g bounty and agro'd the husband
