### ISSUE TITLE
Dead link in the "Helpful Links" section of the wiki

### ISSUE THREAD

**Issue by GuntranHoet** [tiltedphoques/TiltedEvolution#315]
Dead link when clicking the "Reporting Bugs/Requesting Features" page in the "Helpful Links" section of the wiki (https://wiki.tiltedphoques.com/tilted-online/general-information/helpful-links#reporting-bugs-requesting-feature).

I'm assuming this should link to here: https://github.com/tiltedphoques/TiltedEvolution/issues/new/choose

**Comment by Dragonisser** [comment]
https://wiki.tiltedphoques.com/tilted-online/general-information/helpful-links There, fixed
