### ISSUE TITLE
UI: mark your party members

### ISSUE THREAD

**Issue by DLumi** [tiltedphoques/TiltedEvolution#323]
## Description

A feature that enables you to see your party members behind map geometry.

## Additional context

I always lose my partner in bushes/rocks/dark etc. Being able to tp to them is nice, but it would be way cooler if there was an indication of their position like a marker above their head, or on the compass. Or maybe draw an outline around teammates when they are out of LOS. Whichever works best while not ruining immersion.

**Comment by kulcris** [comment]
Author of this mod stated they will update the mod soon, 
https://www.nexusmods.com/skyrimspecialedition/mods/23516
I used to use it on nightly and it worked pretty good

**Comment by jjnether** [comment]
Player markers is a feature in progress #202

**Comment by Dragonisser** [comment]
> Player markers is a feature in progress #202

Thats MAP markers, not markers like quest markers.

**Comment by DLumi** [comment]
> > Player markers is a feature in progress #202
> 
> Thats MAP markers, not markers like quest markers.

Better than nothing, I guess. But, yeah, I was talking about something along the lines of quest markers but for party members.
By the way, doesn't quest marker system already have an option to mark npcs? Couldn't that be repurposed?

**Comment by xForcer** [comment]
If everything turns out fine in testing, this feature should be available soon!
@DLumi

**Comment by Dragonisser** [comment]
Added in 1.6.5
