### ISSUE TITLE
Healing Spell not working

### ISSUE THREAD

**Issue by rlberry** [tiltedphoques/TiltedEvolution#328]
Spell Healing Hands does not heal party member.

Steps to reproduce:
1. Be Party Leader
2. Take damage
3. Have Party Member try to use Healing Hands spell (which is targeted)
4. Note health does not regen

**Comment by ejektaflex** [comment]
Is this on version 1.2 for both the client and server? This was fixed in 1.1.

**Comment by rlberry** [comment]
That would do it. I did not see the update. Going to go test.
