### ISSUE TITLE
temporary HP boost extending outside of the UI frame

### ISSUE THREAD

**Issue by French-Asgeir** [tiltedphoques/TiltedEvolution#329]
## Description

Didn't get to test for other form of HP boost (potion or enchant) but arkay blessing which give +25hp seems to extend outside of the default HP frame for group member.

Related formIDs|
---------------|

none

## Steps to reproduce

1. Start the game.
2. Load a saved game.
3. Connect to the server.
4. Create a party
5. Ask a friend to connect and join your party
6. You and you friend use any shrine of Arkay.
7. You should now see the HP bar on the top left corner extend out of it's designed frame

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

4 Options : 

![image](https://user-images.githubusercontent.com/109287366/179319469-34ce6d80-32cc-4ea8-a8b5-f1ef65e4972c.png)

Option 2 or 4 would be the best one since it probably won't cause weird behavior when using an absurdly good HP potion (which is easy to do in skyrim

## Evidence (optional)

Forgot the screenshot while playing sorry. The paint above transcript the issue really well

**Comment by Dragonisser** [comment]
Even tho the calculation is basically just health / maxhealth * 100, it seems as maxhealth isn't including this temporary buff.

**Comment by Dragonisser** [comment]
Someone would need to RE to find the actual maxHealth value

![image](https://user-images.githubusercontent.com/4233773/179355184-8f1729b2-f081-41ff-bd03-8208d9b4359d.png)
![image](https://user-images.githubusercontent.com/4233773/179355201-42cffcb7-fb9b-4593-90ff-383a8e21c62e.png)


```
float CalculateHealthPercentage(Actor* apActor) noexcept
{
    ActorValueOwner& actorValueOwner = apActor->actorValueOwner;

    spdlog::info("Sending health information");
    spdlog::info("ActorValueOwner");
   

    const float actorHealth = actorValueOwner.GetValue(24);
    const float actorBaseHealth = actorValueOwner.GetBaseValue(24);
    const float actorPermaHealth = actorValueOwner.GetPermanentValue(24);

    spdlog::info("actorHealth: {}", actorHealth);
    spdlog::info("actorBaseHealth: {}", actorBaseHealth);
    spdlog::info("actorPermaHealth: {}", actorPermaHealth);


    spdlog::info("Different Story");
    const float maxHealth = apActor->GetActorPermanentValue(ActorValueInfo::kHealth);
    spdlog::info("maxHealth: {}", maxHealth);
    if (maxHealth == 0.f)
        return 0.f;

    const float health = apActor->GetActorValue(ActorValueInfo::kHealth);
    spdlog::info("health: {}", health);
    
    float percentage = health / maxHealth * 100.f;
    spdlog::info("percentage: {}", percentage);
    if (percentage < 0.f)
        percentage = 0.f;

    return percentage;
}
```

**Comment by kulcris** [comment]
https://github.com/tiltedphoques/TiltedEvolution/pull/357

Proper fix
