### ISSUE TITLE
Font Size Settings

### ISSUE THREAD

**Issue by Sturlen** [tiltedphoques/TiltedEvolution#331]
## Description

Default text size can be difficult to read on small screens. Would be nice to be able to set font size in the settings menu, even if it's just a couple presets.

## Additional context

Should only need to change the font-size at the root element and it should propagate down, based on what I've seen of the codebase.

**Comment by Dragonisser** [comment]
For that we need to get the dropdown and scrollbar to work with the mouse.

**Comment by Sturlen** [comment]
Could use buttons to increase and decrease size then. Skyrim already has a similar menu control:
<img width="155" alt="difficulty" src="https://user-images.githubusercontent.com/43607012/179469095-deb36af9-c09d-48e2-abfa-9c5582d64d51.png">
<img width="155" alt="font size input" src="https://user-images.githubusercontent.com/43607012/179469112-d69e829b-ef7a-49ac-ae82-794cfcfff815.png">

**Comment by Dragonisser** [comment]
Could be an option, though the issue mentioned needs to be fixed anyway.

**Comment by Sturlen** [comment]
Very true, but I think it might fit better in a separate bug report.

**Comment by Dragonisser** [comment]
Just saying :P
