### ISSUE TITLE
Can't Progress The Dark Brotherhood

### ISSUE THREAD

**Issue by staticrecharge** [tiltedphoques/TiltedEvolution#333]
## Description

After killing Grelod the kind you are supposed to go to sleep so that Astrid can kidnap you and progress the Dark Brotherhood initiation. However because indivual clients can't progress the server time and going to sleep does not progress time either, this part of the quest is broken. Going to "sleep" for any length of time does not progress the Dark Brotherhood.

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Talk to Aventus Aretino.
2. Kill Grelod the Kind in Riften.
3. Go to sleep in any owned bed.
4. Nothing happens.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Astrid should have kidnapped me and taken me to the shack to begin the initiation process after going to sleep in a bed.

**Comment by staticrecharge** [comment]
Nevermind, issues was user error!

**Comment by NotActuallyTerry** [comment]
@staticrecharge could you share how you resolved this? I'm still having trouble with being kidnapped

**Comment by staticrecharge** [comment]
> @staticrecharge could you share how you resolved this? I'm still having trouble with being kidnapped

I forgot to go back and talk to Agents after killing Grelod. After that it worked just fine.
