### ISSUE TITLE
Teleporting while on a horse

### ISSUE THREAD

**Issue by zombieseatflesh7** [tiltedphoques/TiltedEvolution#334]
Teleporting to a party member while on a horse causes you to end up stuck inside the ground unable to see, move, or teleport again.

## Steps to reproduce

1. Join a party
2. Mount a horse
3. Teleport to a party member
4. End up stuck in the ground

## Reproduction rate

- [ x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Teleporting while on a horse should either be disabled, or the player should be automatically dismounted before they teleport.

**Comment by RobbeBryssinck** [comment]
Don't teleport while on a horse. This is a skyrim issue. You also can't use the coc console command while on a horse.
