### ISSUE TITLE
Proper plugin loading pls?

### ISSUE THREAD

**Issue by BStevenson96** [tiltedphoques/TiltedEvolution#346]
## Description

Running Skyrim through Skyrim Together Reborn appears to interrupt the game engine's ability to properly recognize/load .esl plugins and disabled plugins. STR seems to cause ALL plugins to take up a load slot, regardless of form or activation status.

That said, the game will still load with more than 254 plugins, but major issues occur past this point (again, regardless of .esl flags or activation status). Most notably the game starts failing to load in terrain in cells and mod-added objects.

## Additional context

This appears to be specific to ST Reborn, as running the game without the launcher solves the issues above. 

I know that you and your team do not currently recommend or support mods with STR in any capacity. However, having this information available would probably help a lot of chronic modders, like myself, to avoid running into similar plugin limit issues.

**Comment by Astral3** [comment]
Please check if an issue exists or is otherwise known before making a post. 

We have stated numerous times that the ESL loader is currently disabled.

**Comment by Dragonisser** [comment]
Shouldnt be the case anymore for 1.6.5
