### ISSUE TITLE
Multiple items arrows/ potions used in one click

### ISSUE THREAD

**Issue by Marteeen17** [tiltedphoques/TiltedEvolution#347]
Consumables such as potions will use more than one when you want to heal yourself.
For example: If in a party of 3 (including myself), if I have 10 health potions, I click to use ONE for myself. It will use 2-3

Same for arrows: if I draw the bow (I don't even have to shoot), it will consume 1-2 arrows. 

Basically consumables are a bit problematic, especially for archery/ alchemist builds

**Comment by Dragonisser** [comment]
Use the provided template

**Comment by Marteeen17** [comment]
> Use the provided template

and which template would that be?

**Comment by Dragonisser** [comment]
![image](https://user-images.githubusercontent.com/4233773/179426012-1a78c895-d158-4c73-9265-2ac7b0300f4d.png)
