### ISSUE TITLE
Sit Anywhere v2 spawns a cow.

### ISSUE THREAD

**Issue by Raezroth** [tiltedphoques/TiltedEvolution#348]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

## Description

As the title says, Sit anywhere v2 works for both parties and syncs animation. Though it spawns a cow on the other players heads.

When one player has the mod, no cow spawns and only the player with the mod can sit and be seen siting by other players without the mod.

when 2 players have the mod installed, it starts spawning  cows where other players are sitting.

I have not found anything in the mod pex scripts to cause this, though I maybe wrong.

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. 2 people install SkyrimTogether and Sit Anywhere 2
1. Start the game.
2. Load a saved game where your character is in Whiterun standing inside your house.
3. Connect to the server.
4. Sit next to each other.
5. Cow spawns on other players head. 

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Both players sit without cows

## Evidence (optional)

![The Elder Scrolls V Skyrim Special Edition_2022 07 16-17 34](https://user-images.githubusercontent.com/47491977/179379335-e61adcd5-3832-4172-9254-cd5666c22501.png)

**Comment by RobbeBryssinck** [comment]
Don't submit any reports about mods, we don't support them, and you're not even allowed to submit vanilla reports if you're using any kind of mods, as the template explicitly says.

**Comment by Dragonisser** [comment]
![image](https://user-images.githubusercontent.com/4233773/179399779-f83f2307-2117-4808-9a89-7354c01639cb.png)
