### ISSUE TITLE
Crash when connecting to any server

### ISSUE THREAD

**Issue by DyzKira** [tiltedphoques/TiltedEvolution#350]
## Description

The game just closes when trying to connect to any server

## Steps to reproduce

1. Start the game.
2. Load a saved game where my character is in Riverwood.
3. Connect to the server.
4. Game close/crash (Before connecting the game closes)

**Comment by BrSnoww** [comment]
I'm going through the same problem. Any solution?

**Comment by Dragonisser** [comment]
Have you even read the wiki? https://wiki.tiltedphoques.com/tilted-online/guides/troubleshooting/my-game-crashes-when-i-open-it-or-connect-to-a-server
