### ISSUE TITLE
Linux docker server crashes on client with huge amount of mods

### ISSUE THREAD

**Issue by SolSoCoG** [tiltedphoques/TiltedEvolution#351]
## Description

The linux docker server crashes when a client with a huge amount of mods joins it.

## Steps to reproduce

1. Start the server, in my case via docker-compose up.
2. Someone with a huge amount of mods joins.
3. Server crashes

## Reproduction rate

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

It should keep running, at best crash the client.

## Crashlog

```
[...]

verhaul.esp, Praedy's StavesAIO.esp, QuickLootEE.esp, Hothtrooper44_ArmorEcksstra.esp, Hothtrooper44_ArmorCompilation.esp

skyrimreborn01 | [04:03:45] [info] Connection ended 2277123a

skyrimreborn01 | SkyrimTogetherServer: Code/encoding/Messages/NotifyFactionsChanges.cpp:7: virtual void NotifyFactionsChanges::SerializeRaw(TiltedPhoques::Buffer::Writer&) const: Assertion \Changes.size() < 0x100' failed.`

skyrimreborn01 | [9:9:20220717,040408.122563:ERROR elf_dynamic_array_reader.h:64] tag not found

skyrimreborn01 | [9:9:20220717,040408.142591:ERROR elf_dynamic_array_reader.h:64] tag not found
```

trying to restart the server causes this error to pop up several times, probably because of the abruptly crash:

`skyrimreborn01 | [9:11:20220717,113520.097546:ERROR file_io_posix.cc:152] open /home/server/.sentry-native/pending/21908376-a797-4c32-9010-0dc92c56885f.lock: File exists (17)`

**Comment by BennyOfEarth** [comment]
cosideci: "we don't support mods, no exceptions"

From what I've seen in the chats they are just leaving mods in general to other people if they want to make a fork of it, also they say there is no real way to make ST:R support all mods, the mods need to change their mods support ST:R. Probably the same for server issues. Especially with a "huge" amount of mods.

**Comment by Dragonisser** [comment]
Should be fixed.
