### ISSUE TITLE
more then selected % gold loss on death

### ISSUE THREAD

**Issue by French-Asgeir** [tiltedphoques/TiltedEvolution#353]
## Description

The gold loss on death seems to be incorrect. I got from 311 gold to 51 after dying when the gold loss factor is 5%. More over after a few death it's seems to be possible to go 0 gold when starting gold was approx 1100.

Related formIDs|
---------------|
none

## Steps to reproduce

1. Setup you server gold loss factor to 5 %
2. Start the game.
3. connect to server.
4. Accumulate 5000 golds .
5. Buys stuff until only there is 1000 golds left.
6. Procede to die and check your balance.
7. You should lose way more than 50 gold

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Losing the correct amount of gold an death.

## Evidence (optional)

you can only take my word for the amount lost but my server STServer.ini is just below : 

[general]
sLogLevel=info
bConsole=true

[LiveServices]
bAnnounceServer=false

[Gameplay]
fGoldLossFactor=0.05
bEnableXpSync=true
bEnablePvp=true
bEnableGreetings=false
uDifficulty=5

[ModPolicy]
bAllowMO2=true
bAllowSKSE=true
bEnableModCheck=false

[GameServer]
sPassword=
sServerName=Dedicated Together Server
bPremiumMode=true
uPort=10578

**Comment by Dragonisser** [comment]
You pay fines on death.

**Comment by MatiasRepetto** [comment]
I was reviewing the code and there is no trivial bug with the gold loss system. How much gold exactly you loss?, It is constant or variable ?

**Comment by French-Asgeir** [comment]
Alright I got the screenshot for you : 

(I'm on 5 % loss like before by the way)

1. I started with 1673 golds
![Capture1](https://user-images.githubusercontent.com/109287366/179427291-9a91d869-eeaa-42aa-ac67-b3987df8f657.PNG)
2. I buyed for 572 gold an elven armor which mean I now have 1001 golds
![Capture2](https://user-images.githubusercontent.com/109287366/179427336-80d6c2d5-5b03-4f92-95cb-c35b85d349d2.PNG)
3. I kill myself against guard and now have 925 golds
![Capture3](https://user-images.githubusercontent.com/109287366/179427367-de679117-1709-4816-a782-b0628e10ed1f.PNG)

1001*0,95=950,95 which mean my balance should have been 951 or 950 golds instead of 925 golds.

I also tested this when only dropping gold in a chest instead of buying stuff and in this scenario, it's seems to work fine tho.

**Comment by Dragonisser** [comment]
You attacked a guard and had a fine, how much was it?

**Comment by French-Asgeir** [comment]
It's 40 by default, I just tested it's seems to take the 40 golds on death without buying thing from vendor before out of exactly 1000 golds.
It's seems to pays the fine also which I suppose is a correct behavior but don't make me pay the 5% on death then.

**Comment by French-Asgeir** [comment]
I discovered the issue by falling initially, I only tested it this way because it was easier but it seems to add another factor to the mix. Guard or not it doesn't seems to add up.

I will redo the test by dying from falling if needed.

**Comment by ToeKneeRED** [comment]
40 * 0.95 = 38
1001 - 38 = 963
963 - 38 = 925
This may be a coincidence but the gold being subtracted by the death might be the one being affected by the gold?

**Comment by French-Asgeir** [comment]
well there is something wrong here : 

- before dying to a giant
![Capture4](https://user-images.githubusercontent.com/109287366/179624247-db34eff0-9622-421d-a91e-2a8d7f483eaf.PNG)

- after dying to a giant 
![Capture5](https://user-images.githubusercontent.com/109287366/179624340-a6e6e4c5-01de-462f-b0c6-8899d5203b82.PNG)

Still on "5%" gold loss per death with no bounty at the moment. There was a message telling me I was losing 361 each death.

**Comment by MatiasRepetto** [comment]
may be a problem with the way that the total amount of gold is obtained from the player later used in the operation.

**Comment by RobbeBryssinck** [comment]
The most likely cause of this problem is that the gold count that the server keeps of the player is incorrect.

**Comment by Dragonisser** [comment]
Stale issue. Closing for now.
