### ISSUE TITLE
Message size [xyz]is too big

### ISSUE THREAD

**Issue by Kog008** [tiltedphoques/TiltedEvolution#355]
Hey guys,

love your work! I have troubles with v1.2. Please check last server console entry. 

![image](https://user-images.githubusercontent.com/25052430/179423715-8de52b26-dec5-4a3c-a4b8-b14a2e969cbc.png)

- reborn Version 1.2.0
- skrip extender version 2.0.20
- adress library 5

Randomly reproducable after a few seconds to minutes on a local server together with a friend using hamachi as lan tool.

Any hints?

Keep going and

kind regards,
Gabriel.

**Comment by Sturlen** [comment]
Have you tried running the mod without SKSE? It is not required for the mod to function.

**Comment by Kog008** [comment]
No, I did not. I go for it tomorrow. . I thought it was mandatory, because vortex suggested it to me. Nevertheless, I had no issues with reborn 1.0/1.1..

Thank you for your quick answer - I am going to respond tomorrow.

**Comment by kulcris** [comment]
This is an error in a dependency happening here, 
https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_connections.cpp#L2057

Are you connected to steam?

**Comment by Dragonisser** [comment]
Besides whatever exactly is going on, we dont support mods.
