### ISSUE TITLE
Unpause game while reading books

### ISSUE THREAD

**Issue by Sturlen** [tiltedphoques/TiltedEvolution#356]
## Description

As mentioned on the discord server, being able to read a book and still take in the world around you would be great.
Since a lot of other menus are unpaused, I belive this should be possible.
## Additional context

This feature is already implemented by the mod [Skyrim Souls RE](url) and I've included snippets of what I believe could be relevant for reverse enginnering below:

https://github.com/Vermunds/SkyrimSoulsRE/blob/master/src/Menus/BookMenuEx.cpp
```
void BookMenuEx::InstallHook()
	{
		//Hook AdvanceMovie
		REL::Relocation<std::uintptr_t> vTable(Offsets::Menus::BookMenu::Vtbl);
		_ProcessMessage = vTable.write_vfunc(0x4, &BookMenuEx::ProcessMessage_Hook);
		_AdvanceMovie = vTable.write_vfunc(0x5, &BookMenuEx::AdvanceMovie_Hook);
	}
```

https://github.com/Vermunds/SkyrimSoulsRE/blob/master/include/Offsets.h
```
            namespace Console
		{
			static constexpr REL::ID Vtbl(static_cast<std::uint64_t>(215002));
		}

```

**Comment by Dragonisser** [comment]
It is either an oversight or intended.

**Comment by Sturlen** [comment]
Did some digging in the code myself and found the unpausing functions. Added "Book Menu" to the list and tested it.
Book menu was indeed unpaused, but no book was visible. Had to force close the game afterwards to get out.

It seems this won't be an easy fix and is certainly outside my area of expertise, but if anyone else is interested a good place to start would be here:

https://github.com/tiltedphoques/TiltedEvolution/tree/master/Code/client/Games/Skyrim/Interface/UI.cpp

**Comment by Dragonisser** [comment]
It was intentionality paused because it breaks the game.
