### ISSUE TITLE
Conjuration Build - Fixed summons

### ISSUE THREAD

**Issue by TheZeusk** [tiltedphoques/TiltedEvolution#361]
Is there any way in the future to change the AI ​​of friends a bit so that summons don't attack friends?  I really like to play as a Conjurer and I think other players do too, but with this problem it is difficult at least for me every time I try to summon summons almost 100% of the time they attack my friends.  I had to redo my entire build of the game due to this AI issue.

**Comment by Dragonisser** [comment]
Duplicate https://github.com/tiltedphoques/TiltedEvolution/issues/294
