### ISSUE TITLE
[CEF] Handle PET_POPUP

### ISSUE THREAD

**Issue by Dragonisser** [tiltedphoques/TiltedEvolution#362]
Currently CEF doesn't handle **PET_POPUP**, only PET_VIEW. Removing the check doesn't change anything.

https://github.com/tiltedphoques/TiltedUI/blob/master/Code/ui/src/OverlayRenderHandlerD3D11.cpp#L127=

Not really an issue for this Repo but whatever -> https://github.com/tiltedphoques/TiltedUI

### Maybe helpful links

https://magpcss.org/ceforum/apidocs3/projects/(default)/CefRenderHandler.html#OnPopupShow(CefRefPtr%3CCefBrowser%3E,bool)

https://github.com/bkeiren/cef/blob/master/tests/cefclient/browser/client_handler_osr.cc#L81

https://blog.katastros.com/a?ID=00500-91c97f9d-f227-4282-8992-2f41ca4d0c6e#:~:text=to%20be%20intercepted-,Render%20Popup%20popup,-In%20the%20browser

https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12806

**Comment by scomans** [comment]
For the select problem: `PET_POPUP` is not rendered in `OnPaint`

**Comment by Dragonisser** [comment]
https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=12806

See CefRenderHandler OnPopupShow, OnPopupSize and OnPaint with a |type| value of PET_POPUP.

Someone would need to adjust the CEF core code.

**Comment by Dragonisser** [comment]
For whatever reason the image doesnt load.

![image](https://user-images.githubusercontent.com/4233773/180661461-ff7ce14e-9550-43be-9bab-503489bca3c9.png)

**Comment by Dragonisser** [comment]
Solved with with custom dropdowns
