### ISSUE TITLE
More than one consumable used when in a party of 3

### ISSUE THREAD

**Issue by Marteeen17** [tiltedphoques/TiltedEvolution#363]
## Description

When using arrows or consumables (Potions), it uses more than one while in a party. Specifically, when the party host and 2 others are playing, the game will use 2-3 of an item. Even when just drawing your bow and not shooting it will consume arrows.

So 10 arrows or potions will turn into 3-5 usable items

## Steps to reproduce

1. Get in a party of more than 2
2. use bows and arrows, or consume potions and foods

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Thought about making a archer/ alchemist build. Might be a bit problematic when I'm using more potions and arrows than needed.

**Comment by Marteeen17** [comment]
> While I'm certain it happens (experienced it constantly myself), I'm unsure if the other players can receive the effects). Some of my friends mentioned seeing the visual effects when I was eating alchemy ingredients, but I still need to check on that.

Actually I've tested that one out too. It consumes too many alchemy ingredients at once and the effects of the ingredients spread out across the party. 

Occurs 100% of the time, very reproducable

**Comment by kulcris** [comment]
Strangely enough... this fixes the arrow issues.... but not the consumables 
https://github.com/tiltedphoques/TiltedEvolution/issues/367#issuecomment-1190956400

**Comment by RobbeBryssinck** [comment]
#387

**Comment by MitchellCalder** [comment]
> I have been working on this for the better part of 2 days.
> 
> From what I can tell. The remote player is seeing the inventory update BEFORE the action actually happens and the only thing that is happening during that time is the syncing of the animation.
> 
> For example, when you DRAW an arrow (not even shoot) the remote player takes the arrow. Then the local player shoots the arrow resulting in another negative.
> 
> If the local player Draws the arrow BUT DOES NOT SHOOT The arrow is still reduced by the remote player. The next time the local player pulls back the bow it DOES NOT take the extra arrow.
> 
> I believe it the remote player is applying player logic to what is essentially an NPC (NPCS do not consume items like arrows or potions) Since the bowdraw player animation is applied to an NPC it is assuming the player finished the animation resulting in consumption.
> 
> At this point is it still theories but I was able to prevent it from happening by essentially blocking remote players from updating other player's inventory.
> 
> But sadly this would also break pickpocketing .

If I am understanding you correctly this would just break players pickpocketing each other right? If so isn't that already broken? https://github.com/tiltedphoques/TiltedEvolution/issues/367#issuecomment-1190956400

I know this isn't a democracy but if that is the case I think I would consider this to be a big enough issue it might be worth implementing in the short term until a more permanent fix can be found. Just my $0.02.

**Comment by kulcris** [comment]
Pickpocketing is only broken because the other player is marked as a
follower.
