### ISSUE TITLE
Enchanted items not staying enchanted for other players

### ISSUE THREAD

**Issue by Scareth96** [tiltedphoques/TiltedEvolution#365]
My group of 4 has been playing the game where we each have an assigned role and profession

We've been feeding all of our enchants to our enchanter in the group so that he can get it leveled up and can enchant us some gear. However, when he enchants an item and drops it for another player, the item does not stay enchanted and reverts back to its original state. For example, our enchanter crafted a restoration enchantment on steel armor for our healer but after he enchanted it and dropped the item it had reverted back to just basic steel armor from the healer's perspective. Kind of ruins the whole point of what we wanted to do. Is there anyway it can be fixed or has anyone found a workaround?

**Comment by Dragonisser** [comment]
Use the template and dont delete it.
