### ISSUE TITLE
Can no longer pickpocket players after v1.1.0

### ISSUE THREAD

**Issue by marklang1721** [tiltedphoques/TiltedEvolution#367]
## Description

After the 1.1.0 update pickpocketing is no longer an option on other player characters and is replaced by a "talk" prompt. If you hold down the interaction key the target reticle changes to the same one you use to give commands to Followers.

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Start the game.
2. Load a saved game.
3. Connect to the server with other players on it.
4. Walk up to another player.
5. Crouch and move your reticle over them.
6. Observe that no pickpocket option shows up and only give you the option to talk.
7. Hold the interact key and observe your reticle changing to the Follower Command reticle.
8. Try to issue commands to the other player fruitlessly while you lament that you can't retrieve the gold that this loot goblin just stole from the chest you were about to loot.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

To be able to pickpocket the greedy players and redistribute wealth with the rest of the party, or to be a greedy player and redistribute the party wealth into your inventory. Ideally, pickpocketing should be a server option like PvP, so that it's an opt in.

## Evidence (optional)

Show us what happened.

**Comment by kulcris** [comment]
By disabling this function it fixes this issue. Do we need to set as a teammate or does just setting the player faction work? 
@RobbeBryssinck 

https://github.com/tiltedphoques/TiltedEvolution/blob/2b2585794433a8cd13ccc2e4107902ef0ab944e7/Code/client/Games/Skyrim/Actor.cpp#L446
