### ISSUE TITLE
Custom Race support

### ISSUE THREAD

**Issue by Kekor** [tiltedphoques/TiltedEvolution#369]
Completely mod compatibility related I know but Modding is a big part of what makes elder scrolls games fun, including this one! Currently Custom races do not work properly. Seemingly no matter what custom race mod you have when you have multiple people playing different custom races or even 1 custom race and other races being Vanilla and try to load into any cell the Game will crash. We tested this multiple times with multiple races all of which work in single player however in STR having anyone being a custom race with others being any other race crashes will commence on loading cells. Interestingly enough if all players are the same custom race they will not crash. I'm not sure if it's possible but some sort of compatibility with different custom races in general would be amazing! Not that I know alot about coding but perhaps some sort of function that gets the file directory of the race the player is before referencing the directory for that race while replicating to the other players since they wouldn't be Vanilla assets?

**Comment by RobbeBryssinck** [comment]
This mod does not support other mods. Won't fix.
