### ISSUE TITLE
False Save Corruption Bug Fix(Maxstudio File Handle increase to 2048 instead of 512(Skyrim's default))

### ISSUE THREAD

**Issue by FedUpWizard** [tiltedphoques/TiltedEvolution#370]
## Description

SSE Engine Fixes contained a Fix for False Save Corruption, but Skyrim Together Reborn doesn't, restarting game will allow you to load the saves, but eventually it will happen again. The bug is caused by Skyrim trying to read too many files which is capped by 512 without SSE Engine Fixes(Includes bsa, esp, esm, esl, dll,). This bug appears with a heavy modlist, I believe above 255 plugins that includes esl and ESP flagged as esl, which means the Esl reader(I think) could TEMPORARILY fix this issue unless someone has mods over that 255 limit excluding esl. This bug only occurs for me when connected to the server and playing with a friend, on single player. I have played for more than 4 hours without this bug occurring and I'm quite sure its because of the esl counting as well when connected to a server. 

## Additional context

This is on the SSE Engine Fixes Changelogs on Nexus:
- Version 2.4.0

  > add a patch to set max stdio file handles to 2048 instead of system default 512; this should fix the false save corruption bug in 99.9% of use cases

https://www.nexusmods.com/skyrimspecialedition/mods/17230 Link to SSE Engine Fixes Nexus Page

![image](https://user-images.githubusercontent.com/109249618/180090443-7c7e14ec-211a-470c-a861-0fc32f7ce697.png)

**Comment by FedUpWizard** [comment]
Thank You Dragonisser for the help :)

**Comment by VENDETTA5** [comment]
Yeah, everyone's modded game breaks without this. I had to remove 100(Ended up with 186) mods to be able to play just because of this because I can't do quests with my comrade because dialogues break without this fix. If you will want to make a special modlist for your server you gonna crash into this problem. This bug limits all the possibilities.

**Comment by FedUpWizard** [comment]
Links that may be useful:
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?redirectedfrom=MSDN&view=msvc-170
https://docs.microsoft.com/en-us/cpp/c-runtime-library/stream-i-o?view=msvc-170
