### ISSUE TITLE
Reimplement the animation system to allow modded animation graph.

### ISSUE THREAD

**Issue by edho08** [tiltedphoques/TiltedEvolution#372]
## Description

STR broke walking animation when used with behavior altering mods that uses Nemesis/FNIS resulting in remote player and npc sliding around yet the animation are playing fine on local player. The walking animation does actually play on remote player and npc but it does so in slow motion. One can sped up the animation playback speed to see npc and remote player walking with less sliding but when local player move, the animation play really fast. This feature request is made primarily because Nemesis used to work just fine on harbor even with mod mismatch yet broke on STR. I would like the dev to consider this feature request to be the least priority right now and rather to work on a more game breaking bug and crashes fix.

## Additional context

This is a mod compatibility issue hence its a feature request rather than a bug report. Any bug fixing attempt from Nemesis/FNIS end is very encouraged as the vanilla behavior files worked just fine with STR.

**Comment by edho08** [comment]
## Description

Adding any custom behavior variable into 0_master.hkx and horsebehavior.hkx causes broken walking animation in remote player and npc. Other behavior files hasn't been investigated yet. Is behavior variable hardcoded in STR?

## Steps to reproduce

1. Add any custom behavior variable into 0_master.xml or horsebehavior.xml
2. Compile the .xml file to .hkx file using hkxcmd
3. place file to data/meshes/actors/character/behaviors
4. Boot up Skyrim Together
5. (Optional) join on a server
6. See remote player and npc sliding around

## Reproduction rate

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Remote player and npc have correct walking animation

**Comment by RobbeBryssinck** [comment]
This would require us fundamentally revamping animation sync to support mods. We don't support other mods. Won't fix.
