### ISSUE TITLE
Preset Parties on server

### ISSUE THREAD

**Issue by BobFigGreen** [tiltedphoques/TiltedEvolution#378]
Add option to create preset parties in server options
Due to crashes at the moment inviting people to parties all the time can become tedious
Would be very grateful if this feature could be implemented

**Comment by BobFigGreen** [comment]
Or possibly add option to set a party leader for whole server

**Comment by Sturlen** [comment]
Would be difficult to do, since you don't have a permanent user id or a login for the server. Right now the only thing the server has is your player characters name, and anyone can log in with any character name or even the same one.

**Comment by BobFigGreen** [comment]
> 
True but even adding an option using character names would be fine for private servers as it would only need changing when making new characters 

I understand that this may not be possible though

**Comment by Gibbit2k** [comment]
This should be achievable and really useful on small private servers:

1. Add a party leader line to the server config where the party leader nickname is specified
2. When connecting to server beside ip ask for a nickname 
3. If nickname is the one specified in server config connect to server and create party
4. If nickname is not the one in server config check if party leader is on, if true connect and join party automatically if not don't allow connect to server until party leader is on
5. Alternatively you could force dc all users if the party leader crashes or disconnects or something to try and mitigate sync errors.

**Comment by Owlchemist** [comment]
> Would be difficult to do, since you don't have a permanent user id or a login for the server. Right now the only thing the server has is your player characters name, and anyone can log in with any character name or even the same one.

Well, if someone wanted to troll you, there are _far worse_ things they can do than grief your party composition. As I understand it the main development direction was playing with your friends, I think it'd be a nice bit of polish for non-public servers at least.

**Comment by Sturlen** [comment]
It would still generate a lot of edge cases that need to be handled, even
if noone is aiming to be malicious.

I think it would be better to focus on making making inviting people
easier, such as clicking on their name in chat and being able to accept
without going into menus.

**Comment by jjnether** [comment]
Best solution would be the feature mentioned in #404

**Comment by isaaclw** [comment]
Agreed. If there are no parties, then the auto-join or auto-invite system can be turned off. The majority of the bugs happen with non-party members anyway (ie: crafting/inventory)

**Comment by Dragonisser** [comment]
Added in 1.6.5
