### ISSUE TITLE
Better player aggro

### ISSUE THREAD

**Issue by RobbeBryssinck** [tiltedphoques/TiltedEvolution#382]
The game puts a high priority on "the player" to target in combat. Simply marking the other players as followers helps a little bit, but ultimately, the enemies will still favor the host player. To fix this, a system must be created that actively switches the combat states between players. These functions are a good start:

https://www.creationkit.com/index.php?title=GetCombatTarget_-_Actor
https://www.creationkit.com/index.php?title=IsInCombat_-_Actor
https://www.creationkit.com/index.php?title=StartCombat_-_Actor
https://www.creationkit.com/index.php?title=StopCombat_-_Actor

Use the `feat/player-agro` branch to work on this.

**Comment by Sturlen** [comment]
Would it be possible to mark the host as "just a follower" instead of "the player"? If so, it should split the aggro more evenly.

**Comment by RobbeBryssinck** [comment]
No, the game relies fairly heavily on form 0x14 being "the player".

**Comment by Sturlen** [comment]
I suspected it would be too easy, but it's good to cover all avenues.

**Comment by DJLegends1011** [comment]
also keep the play faction feature tht you implemented cosi its working flawless!!
that that didn't synced now does on my end!

**Comment by cairomn** [comment]
In this case, it's possible verify the armor of player and determine the tank of team? And this tank get the aggro of monsters?
I think this solution it's interesting. But needs a better adjust.
Because, the Mage with Armor Spells come get more armor than tanks, sometimes.

Sorry, I think I dreaming here.
