### ISSUE TITLE
Prevent consumable sync

### ISSUE THREAD

**Issue by RobbeBryssinck** [tiltedphoques/TiltedEvolution#387]
Activation sync also syncs activated consumables, like healing potions, food, and ingredients. These need to be excluded, otherwise items doubly disappear, screen effects appear on all screens, UI components pop up on all screens, magic effects are applied double, etc.

**Comment by kulcris** [comment]
https://github.com/tiltedphoques/TiltedEvolution/issues/380
Same issue

**Comment by LiamKarlMitchell** [comment]
Using useable items from favourites Q menu eats more than 1, even when I put them on a HotKey like 1,2,3.
Same issue?

**Comment by Dragonisser** [comment]
fixed in #554
