### ISSUE TITLE
Server is not reading ini file

### ISSUE THREAD

**Issue by Vexthecollector** [tiltedphoques/TiltedEvolution#391]
## Description

The server is not reading my ini file after creating it via docker on linux and pointing it to the file. I set a password and it does not read the password.

docker run command:

docker run -d -it --name skyrimserver -p 10578:10578/udp -v /home/steam/games/skyrim/config -v /home/steam/games/skyrim/server/Data -v /home/steam/games/skyrim/logs tiltedphoques/st-reborn-server:latest 

## Steps to reproduce

Create the image. See it not pull up the ini file.

## Reproduction rate

100%

## Expected result

It reads the ini file

**Comment by RobbeBryssinck** [comment]
https://wiki.tiltedphoques.com/tilted-online/guides/server-guide/linux-setup/docker-setup

**Comment by Vexthecollector** [comment]
The guide only explains how to install it in the /opt/ location, which not everyone might want to. Installing it outside of there seems to lead to this issue.

**Comment by RobbeBryssinck** [comment]
You're using the -v parameter incorrectly.
