### ISSUE TITLE
Non host player crashes when Dragon switches aggro [bug] 

### ISSUE THREAD

**Issue by matorina22** [tiltedphoques/TiltedEvolution#393]
Bug happens to a non party host member in group of two players.
If you target the dragon while in air with your reticle or just look at him directly or he switches his attack stance to you, the game instantly freezes to crash. 
Happens every time when dragon turns his head to the second non host player and wants to initiate attack on him.
Tried to mitigate this by never looking at the dragon while in air and only attacking it on the ground it it worked I think.

**Comment by Dragonisser** [comment]
Use the template.
