### ISSUE TITLE
Possible solutions for death desync.

### ISSUE THREAD

**Issue by Imn0tac0p** [tiltedphoques/TiltedEvolution#402]
So, I think the issue is, when a player dies, the game is loading their last save, which is client side and isn't syncing with other players, causing desync to continually worsen over time, and be atrocious in dungeons. This causes everything to go back to how it was for all players when the dead player entered the dungeon and desyncing the area with anyone who had lived.

add a server-side saving system for world events, allowing servers to save the data instead of the player. The issue with this is, making specific things server-side vs client-side. Not sure how Skyrim's save system would interact with this tbh.

Quests, NPC deaths, item spawn/despawn (drop/pickup), interactions with animated props (things like levers that effect drawbridges, etc) could all be synced server-side. You likely wouldn't even need to touch clinet-side saving. Just have the respawn script overwrite the client-load with the server-side data, keeping whatever player info, inventory, etc, that wasn't touched by the server-side save.

Add a toggle on/off switch for server owners to choose if they want this (like with PVP) to avoid quest's becoming unavailable over time. Or, if the server wants to for RP, they could keep it on and maintain an evolving world.

**Comment by Dragonisser** [comment]
Have you even played the latest version? Save reloading hasn't been a thing for 3 years.

**Comment by Imn0tac0p** [comment]
Running 1.2.0 off nexus.  When me or my friend dies, the dungeon still desyncs unless we quicksaved immediately before dying. Basically everything not saved in the dungeon desyncs.

Am I on the wrong version or something?

**Comment by Dragonisser** [comment]
> Running 1.2.0 off nexus. When me or my friend dies, the dungeon still desyncs unless we quicksaved immediately before dying. Basically everything not saved in the dungeon desyncs.
> 
> Am I on the wrong version or something?
> 
> Essentially, the dungeon reloads to whoever died's last save.

Are you using mods? Even the 4 mods that come with 1.6 are mods that shouldnt be used.

**Comment by Imn0tac0p** [comment]
Unofficial patch, Alternate Start, SkyUI, and SKSE, but not running off of skse.exe

**Comment by Dragonisser** [comment]
Remove the mods.
