### ISSUE TITLE
Soul trap crashes on certain animals when using AMD processors

### ISSUE THREAD

**Issue by Bchang21** [tiltedphoques/TiltedEvolution#403]
the soul trap spell causes crash to desktop when used on certain creatures. Repeatable on PCs with AMD processors, seems to have no issue with intel processors.
The list of animals that cause CTD so far:
Chickens,
Cows, 
Goats,
Foxes,
Elk
Possibly other animals that don't have attack animations.

**Comment by Dragonisser** [comment]
Use the template
