### ISSUE TITLE
Automatic party invites 

### ISSUE THREAD

**Issue by meshik** [tiltedphoques/TiltedEvolution#404]
## Description

Crashes are inevitable. A tedious aspect of this involves getting an invite again from the party leader, who may be busy in dangerous combat from the time before you crashed. If I could get a party invite automatically as I connect, I can seamlessly re-join the battle.
This feature is ideal for private servers of consistent friends (of which there are many).

## Implementation

Launching a party in an auto-invite-enabled server makes it so any subsequent connection receives an invite to this party. Add a toggleable feature to the server (default is off) where one can specify if auto-invites should be used.

**Comment by RobbeBryssinck** [comment]
Tbh if we're gonna go this route, it'd be better to just auto join a party on joining a server, instead of auto inviting someone. Takes away another step of having to go through the menus to accept an invite.

**Comment by KevinfromHP** [comment]
I'll look into creating an auto-party config. I was already in the process of something similar but this sounds easier

**Comment by Dragonisser** [comment]
Added in 1.6.5
