### ISSUE TITLE
Soul trap crashes on certain animals when using AMD processors

### ISSUE THREAD

**Issue by Bchang21** [tiltedphoques/TiltedEvolution#406]
no mods installed

## Description

the soul trap spell causes crash to desktop when used on certain creatures. Repeatable on PCs with AMD processors, seems to have no issue with Intel processors. The soul trap effect from an enchanted weapon doesn't seem to cause this issue. Does not need to be connected to multiplayer to cause this bug. Bug also does not happen when running the game through skse, only through the skyrim together executable

Related formIDs|
---------------|
[Soul Trap Effect- 0004dba4](https://en.uesp.net/wiki/Skyrim:Conjuration_Spells#Soul_Trap)|
[Soul Trap Spell - 0005b452](https://en.uesp.net/wiki/Skyrim:Soul_Trap_(effect))|

## Steps to reproduce
1. Have AMD Processor
2. Start the Skyrim Together Executable
4. Cast the Soul Trap Spell.
5. hit a chicken, elk, cow, fox, possibly other animals.
6. Crash to Desktop

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Able to cast soul trap on all animals with no issue

## Evidence / Exception Analysis
[STCrashDump.txt](https://github.com/tiltedphoques/TiltedEvolution/files/9181813/STCrashDump.txt)

**Comment by noahbfoster** [comment]
This issue also occurs on my system, and I am running an Intel i7-7700k and a Nvidia 3080.

**Comment by stenliis** [comment]
The issue is not AMD specific, can be reproduced on my system (i7-7700HQ + NVDIA 1060) with dev build based on bd1a3c8fdfee864dc409a403f59345d508e03b76.

My crash dump is different, maybe caused by 1.6.629 update.

[STCrashDump.txt](https://github.com/tiltedphoques/TiltedEvolution/files/9591778/STCrashDump.txt)
