### ISSUE TITLE
Damaging a dead actor will trigger the game to add more loot to its corpse

### ISSUE THREAD

**Issue by TheMourningWolf** [tiltedphoques/TiltedEvolution#409]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

## Description
When you damage a corpse of an animal or person it will roll additional loot and add it to the corpse, this can be seen in real time with players watching its inventory.

Related formIDs|
---------------|

## Steps to reproduce
With multiple people find an animal/actor and kill it. Ocassionally when another player attacks the killed actor it will not realize it is fully dead and the loot has already been added so it will keep adding loot.
1.) Kill a goat with flames spell.
2.) Have another player view its inventory (unknown if the player burning the goat needs to not be the one that killed it or not)
3.)Have the player not in its inventory burn the corpse with flames spell and watch the numbers of items shoot up quickly into the thousands if done long enough.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [X ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"

## Evidence (optional)

Show us what happened.

**Comment by Dragonisser** [comment]
Already fixed.

**Comment by Speedwagen** [comment]
does seem to be when a player damages a mob that has a higher health pool than the one you can see which you yourself has killed.

**Comment by Dragonisser** [comment]
> does seem to be when a player damages a mob that has a higher health pool than the one you can see which you yourself has killed resulting in that mob getting "killed" repeatedly.

No, its due the fact that killmoves dont kill enemies completely, which means they got a weird amount of health and you basically insta kill them on one end over and over which then spawns loot. Noticeable if using fire.

**Comment by Speedwagen** [comment]
ahh, that makes sense! I was using sparks one time and it generated a ton
of potions. I don't have this mod installed for the record, but if say you
used the Violens mod to disable kill moves could this work as a bandaid fix
around this?
