### ISSUE TITLE
Game is using integrated GPU from CPU instead of gaming GPU.

### ISSUE THREAD

**Issue by Pronown** [tiltedphoques/TiltedEvolution#422]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

- No mods installed

## Description

A clear and concise description of what the bug is, Include any formIDs relevant for us to use ie,

Game is using integrated GPU from CPU instead of gaming GPU.

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Start the game.
2. Look at which GPU is being used.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"

I expect it to use my GPU,  Like the game usually does. Instead it uses the integrated GPU

## Evidence (optional)

Show us what happened.

Possibly same issue as this one, but nothing is actually shown on here to fix it, so I am opening an issue to find a fix. https://github.com/tiltedphoques/TiltedEvolution/issues/34

**Comment by Astral3** [comment]
Hi, please expand the provided information;

Have you tried designating the correct GPU within your gpu control panel, specifying that the .exe run on your main graphics card? Does any change occur?

**Comment by Pronown** [comment]
Well, I was unaware I could do that. Learned something new today. Cool. Fixed. Thanks!

**Comment by Astral3** [comment]
@Dragonisser This can be closed.
