### ISSUE TITLE
Skyrim Together Reborn crashes at random intervals.

### ISSUE THREAD

**Issue by ItsJakObi1** [tiltedphoques/TiltedEvolution#434]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

## Description

My game crashes at random intervals, could be 5 hours of playing, could be 10 minutes. 

A clear and concise description of what the bug is, Include any formIDs relevant for us to use ie,

The ced_debug.log files crash error states:
[0730/141225.106:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 

I have provided the full document.
[cef_debug.log](https://github.com/tiltedphoques/TiltedEvolution/files/9227064/cef_debug.log)

Related formIDs|

N/A

## Steps to reproduce

N/A / I can't find a discernible way to reproduce the crash. It sometimes happens when hard saving, sometimes when fast travelling (with autosaves of any kind turned off), sometimes when just walking around.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [x ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"

## Evidence (optional)

Show us what happened.

**Comment by RobbeBryssinck** [comment]
This is very general. We can't really do anything with this.
