### ISSUE TITLE
Add missing options to STServer.ini config file

### ISSUE THREAD

**Issue by Technoguyfication** [tiltedphoques/TiltedEvolution#445]
## Description

If options are accidentally deleted from the STServer.ini config file, they are never regenerated when the server starts back up, and the server silently assumes the default options for all missing keys.

I suggest that the server either adds missing options, or (what would be much easier) is to simply Save the configuration file _after_ reading it so all the current config options are written back to the file, including custom ones set by the server admin.

## Additional context

For example, if my STServer.ini config file consists of only this:
```ini
[GameServer]
uPort = 27005
```
...the server will start up fine and use port 27005 like I instructed it to, and assumes default options for all other parameters. However, if I want to change anything else I have to look up the parameter name and add it manually or regenerate the whole file and apply my changes again.

**Comment by RobbeBryssinck** [comment]
Why would you delete options?

**Comment by Sturlen** [comment]
If you write `/help` in the server console it regenerate all missing fields while keeping your edited ones, so this isn't really an issue.

**Comment by Technoguyfication** [comment]
> Why would you delete options?

Well in my specific use case, I'm using a script that generates the STServer.ini file and I want it to fill in any options the script doesn't insert into the file. 

However, this feature would make sense just as a future proofing method. When more parameters are added in future releases, it would automatically upgrade people's config files by adding the new parameters to them. Otherwise people will have to add the options by hand or delete the file and let it regenerate.

**Comment by Sturlen** [comment]
> However, this feature would make sense just as a future proofing method. When more parameters are added in future releases, it would automatically upgrade people's config files by adding the new parameters to them. Otherwise people will have to add the options by hand or delete the file and let it regenerate.

As I said earlier, using `/help` does exactly this. You don't need a script.

**Comment by Technoguyfication** [comment]
> > However, this feature would make sense just as a future proofing method. When more parameters are added in future releases, it would automatically upgrade people's config files by adding the new parameters to them. Otherwise people will have to add the options by hand or delete the file and let it regenerate.
> 
> 
> 
> As I said earlier, using `/help` does exactly this. You don't need a script.

Why not take that functionality and run it on server startup? The fact that `/help` does this is pretty unintuitive. I could see a command like `/updateconfig` being a solution. 

However, the setup process I'm using doesn't allow me to automatically run commands after startup. I understand that's not a problem for your team to solve, but it would be more elegant if it was automatic.

**Comment by RobbeBryssinck** [comment]
I see your point now. If someone wants to make this a reality, I'd allow the PR to go through.

**Comment by Sturlen** [comment]
I can take a look at it, should be a pretty simple edit since the functionalty is already there.
