### ISSUE TITLE
No controller support

### ISSUE THREAD

**Issue by Hermsmegerms** [tiltedphoques/TiltedEvolution#446]
When launching skyrim using the skyrim together reborn exe the game does not recognize any input form any type of controller. I connect. 

This issue is not present when launching the game directly from steam or from script extender

Controllers tested :Xbox 360, Xbox one, ps5, and stadia. 
All controllers work when launching the game normally but when launching with skyrim together reborn they do not work. 

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, i.e.

1. Start game
2. Check settings for "controller" chekc box
3. Even with box check the game will not recognize controllers

## Reproduction rate

- [ x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"

 That the game would let me play using any of the controllers that work in vanilla

**Comment by Hermsmegerms** [comment]
With further testing I was able to get the Xbox controllers to work again by disabling steams controller configuration. But the rest of my controllers still do not work.

**Comment by bobbyroylee** [comment]
I was able to solve this problem by using DS4Windows

**Comment by Speedwagen** [comment]
> I was able to solve this problem by using DS4Windows

I would say that's a workaround not a fix

**Comment by Sturlen** [comment]
> With further testing I was able to get the Xbox controllers to work again by disabling steams controller configuration. But the rest of my controllers still do not work.

![bilde](https://user-images.githubusercontent.com/43607012/184167976-6ab009c7-6b73-45f1-ac04-ad3ba4e203fc.png)
If you haven't already, try adding SkyrimTogether.exe as a non-steam game. If you then launch it through steam you should be able to rebind the controller as well.

**Comment by Sturlen** [comment]
> Vortex setup mentions pointing pointing the skyrim together exe to the skyrimse exe.

This a function of SkyrimTogether itself, and if the mod already works you don't need to change anything. Just launch SkyrimTogeher through steam as if it was a seperate game.

**Comment by Speedwagen** [comment]
alright! I might try that tonight.
