### ISSUE TITLE
Make Player Respawn System Optional

### ISSUE THREAD

**Issue by VENDETTA5** [tiltedphoques/TiltedEvolution#449]
## Description

There are mods that implement their own respawn system that conflict with Tilted online and I thought that would be a great idea if there was an option somewhere in clientside/serverside INI files to disable this feature to be replaced with modded ones.
## Additional context
The idea came to me after publishing this:
https://github.com/tiltedphoques/Mod-Compatibility/issues/151
I think this is a great feature for better modding flexibility.

**Comment by Sturlen** [comment]
Probably better handled by a scripting API. such as the one proposed in #8 or the one worked on in PR #289.
