### ISSUE TITLE
Quest synchronisation issue

### ISSUE THREAD

**Issue by microplite** [tiltedphoques/TiltedEvolution#462]
Hello everyone,

I'm posting this because I have an issue with the synchronisation of the quests while playing on skyrim togeter reborn. We got a quest working fine with my friend, but then we need to investigate a bandit camp to find a note, but when I read the note it only actualise the quest for me but not him, and I can't give him the note because it is a quest item.

Thank you

**Comment by VENDETTA5** [comment]
It was probably a radiant quest, none of them syncs st the moment.
