### ISSUE TITLE
DLL Failure Using MO2 on Linux

### ISSUE THREAD

**Issue by Sushiman42** [tiltedphoques/TiltedEvolution#466]
This issue has been mentioned multiple places but I didn't see an open issue on the github page.

When following the install directions for MO2 on Linux, launching SkyrimTogether.exe results in an error `Failed to find dll: bink2w64.dll
Error: 998 = No access to memory `

Myself and others have gotten STR to work with hacky workarounds like manual installation, but it seems to be struggling to launch through MO2 specifically. I have tried to force load the `bink2w64.dll` library through MO2 but this doesn't seem to change anything.

**Comment by Raezroth** [comment]
Currently trying to work around this same issue myself. I would much rather use linux than windows.

**Comment by Raezroth** [comment]
From what I see, it is a bug with running the vfs mo2 has on linux. Vortex works though. It's not mo2 though =(

**Comment by Rafaeltheraven** [comment]
Same here, think it's related to permissions in Steam. Steam puts stuff in a sandbox and I think it's locking access to the required dll

**Comment by Sushiman42** [comment]
I'm wondering if that DLL could be overridden using something like [SteamTinkerLaunch](https://github.com/frostworx/steamtinkerlaunch). I'll try and see if I can it to work if I have some free time.

**Comment by Raezroth** [comment]
It is a bug with Mod Organizer 2.4.4 and Wine on Linux. Download Mod Organzier 2.4.0 from their github to fix this.
https://github.com/ModOrganizer2/modorganizer/releases/tag/v2.4.0
