### ISSUE TITLE
Wolf Has 116 Pelt

### ISSUE THREAD

**Issue by KyChale** [tiltedphoques/TiltedEvolution#470]
Consistent [ ]
Occasional [ ]
Rare [x]

At the hill towards Whiterun by Bleak Falls Barrow and along the path from Riverwood a Wolf had 116 Pelt

**Comment by RobbeBryssinck** [comment]
Fixed in 1.3.0

**Comment by KyChale** [comment]
just happened yesterday

**Comment by RobbeBryssinck** [comment]
1.3.0 isn't out yet.

**Comment by KyChale** [comment]
oh ok
