### ISSUE TITLE
Wood Chopping Block Lock

### ISSUE THREAD

**Issue by KyChale** [tiltedphoques/TiltedEvolution#471]
At a wood chopping block Skyrim Together will make you're character keep pulling out the axe and never stop
(PS this happened at riverwood)

**Comment by Lazalatin** [comment]
To add to this issue, same as when trying to mine ore, this only occurs if other players are nearby.

For the above example, if the chopping player is using the block behind the riverwood mill, it is sufficient for the other players to stay on the other side of the river (i.e. at the inn entrance). Then the animation is continuing as normal.

**Comment by KyChale** [comment]
thanks
