### ISSUE TITLE
NPCs and A Player Not Animating Properly

### ISSUE THREAD

**Issue by Spudkin** [tiltedphoques/TiltedEvolution#472]
## Description

Certain NPCs, as well as one specific player, and occasionally other things like placed objects, will glide along the ground instead of walking. In addition, they use the unarmed animation regardless of weapons equipped, and do not swing weapons when attacking. They simply stand there and damage is dealt. 

## Steps to reproduce

This started during the initial connection, and always affects the same player, even after relogging.

## Reproduction rate

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

The affected entities do not play animations properly, and their position is slightly desynced. The affected player does not see this, only the two unaffected ones do.

**Comment by kaybenot** [comment]
Do you or that person use mods?

**Comment by Spudkin** [comment]
None of us have anything but the bare essentials to run this mod.

**Comment by RobbeBryssinck** [comment]
Does "bare essentials" include any mods?
