### ISSUE TITLE
[Gameserver Config] Add option to force ipv4 usage

### ISSUE THREAD

**Issue by Astral3** [tiltedphoques/TiltedEvolution#473]
#### Description
Some individuals seem to experience an odd issue where the server defaults to using the ipv6 address. A connection can be made over ipv6, but not ipv4.
#### Request Description
Add a config option to force the server to default to ipv4 (Which.. should already be the default?)

**Comment by kaybenot** [comment]
Why should we do it? IPv6 is a better version of IPv4. Not everyone is free of NAT and if one has IPv6 most likely is behind IPv4 NAT.

**Comment by kaybenot** [comment]
IPv6 should be default due to high possibility of NAT when supporting this protocol. Anyway it should be a possibility to change it to IPv4.
