### ISSUE TITLE
Connection issues Skyrim Together Reborn

### ISSUE THREAD

**Issue by Keslake** [tiltedphoques/TiltedEvolution#476]
I just intalled the game and mod following the installation and configuration guide. No other mods added apart from Skyrim Together Reborn. 

I created a server with portfowarding and configurated the .ini file to set a password.

I opened the server and it say that the game will not appear in public services because of the password.

I initiate the game with VMM and after the Helgen mission I joined my server without problems, but my friend does the same and he couldn't connect, the message is that the server doesn't exist or is the incorrect IPv4.

I closed the game and the server then reconfigurated the .ini file so it doesn't had a password and set the bAnnounceServer=True. I opened the server, connected as before without problems and my friend looked for the server game in the public list and it appeared an connected without issue.

The problem is that other players can connect to the server. Any clue to what the issue is? We want a private server to play but I can't get it to work with the password.

**Comment by RobbeBryssinck** [comment]
This is not an issue with the mod, you're doing something wrong. Review the server setup guides on the wiki closely, and if that still does not resolve the issue, ask for help on our discord server.
