### ISSUE TITLE
SkyrimTogetherServer not work properly

### ISSUE THREAD

**Issue by Damala244** [tiltedphoques/TiltedEvolution#496]
I have problem in skyrimtogetherserver 1.3.0
I cannot "/set" any variables
everything always be  "Failed to find setting (Variable)"

many of commands doesnt work too like "/TogglePremium:" always be "Unknown command. Type /help for help."

maybe my setting file corrupted or something? tried delete and reinstall this mod but nothing happen
is there any local setting folder location for this mod or something i need to manual delete too?

sorry for bad english

**Comment by Outshynd** [comment]
To set a variable, the command is `/set <category>:<variable_name>` -- for instance, to set the port to 9999, the command would be `/set GameServer:uPort 9999`

You are also appending a colon (:) to the end of your `/TogglePremium` command.  The colon is just there in the description to divide the command from the explanation.

I would suggest closing this issue and then joining us in the Discord #questions channel if you have other issues.  Your english is quite good, by the way.

**Comment by Damala244** [comment]
I found my problem
its just case sensitive 

thanks for your help
