### ISSUE TITLE
The game is crashing at a random time in a random place

### ISSUE THREAD

**Issue by ItsMercury** [tiltedphoques/TiltedEvolution#518]
The game is crashing at a random time in a random place and I don't know what to do about it. The game crashes without error for me and my two friends with whom I play in a party. This makes the game very uncomfortable.
My friends and I installed the game according to the instructions. We did not install any additional mods, except for the standard mods: SKSE, Skyrim Together Reborn.
We use the method through the program Mod Organizer 2. Please, help!
Add logs below

My logs: 
[cef_debug.log](https://github.com/tiltedphoques/TiltedEvolution/files/9679624/cef_debug.log)

My friend's logs:
[cef_debug.log](https://github.com/tiltedphoques/TiltedEvolution/files/9679680/cef_debug.log)

**Comment by Dragonisser** [comment]
Use the template.
Also SKSE is not and will never be a requirement.
