### ISSUE TITLE
Time won't sync with other group members

### ISSUE THREAD

**Issue by Hexenhub** [tiltedphoques/TiltedEvolution#525]
### **Version of Skyrim Together**
v1.3.2

### **Description**
The time of each group member (in this case 2 with group leader) won't sync with the time of the group leader.

### **Steps to reproduce** (for each player)
1. Start the game.
2. Load a saved game where the character is at any place in the world (does not matter whether both are in the same interior- or outside-place or at different places at the same time).
3. Connect to the server.
4. One of the players is creating a group and invites the other player to join.
5. The other player joins.
6. Time of group member won't synchronise with the time of group leader.

### **Reproduction rate**
- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [x] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

### **Expected result**
I expected that the time of all group members would be synchronised with the time of the group leader after joinig the group.

**Comment by Dragonisser** [comment]
Time sync will be reworked.
