### ISSUE TITLE
Players crash in various circumstances

### ISSUE THREAD

**Issue by KeepBotting** [tiltedphoques/TiltedEvolution#527]
I'm running SKSE and the achievements re-enabler plugin. My three players are unmodded aside from Skyrim Together. I suspect one player might have the Anniversary Edition DLC enabled, though I'm pretty sure he deleted the free Creation Club plugins. I saw in the server console that he had the backpacks plugin loaded, one more plugin than the rest of us. Aside from this I'm fairly certain that everybody's client setup is correct.

I've suggested the process found [here](https://wiki.tiltedphoques.com/tilted-online/guides/troubleshooting/my-game-crashes-when-i-open-it-or-connect-to-a-server) to some users. Verify AES-NI which I'm pretty sure they have or I'd imagine the mods wouldn't run at all, and try clearing out INIs. My people are all fresh installs though, so I don't have high hopes for this bit.

## Versions
The server I built from git master with xmake in `release` mode, it reports version 1.3.2 and is running on Debian testing in an LXC container. The plugin we all downloaded off Nexus, 1.3.2 as well.

## Description

We've played about five hours concurrently together and the mod is _so close_ to being perfect. The way this thing works is amazing. I run the game on Linux (on Steam Deck, no less) and have yet to experience a single crash. My three players are all on Windows and crash occasionally.

One guy seems to crash when _other players_ load cells (not necessarily the cell he's in, either). Another player has only crashed once so far, she was doing something simple with the UI (accessing inventory/favorites menu, don't quite remember). Our fourth player has crashed while equipping items. I am local to the server but one other player is also local, and still crashes.

When the game crashes, it freezes in-place (not quite a CTD) and the program becomes unresponsive. Music can still be heard. Alt+Tab causes the screen to go black. The game must be killed from Task Manager at this point.

During play, we often leave each other's cells (e.g. entering multiple buildings in a town). I didn't see anything on the wiki that said players must be in the same cell at all times but figured this is worth mentioning. The crashes can occur even if all players are together in Skyrim's exterior cell though.

As a troubleshooting step we started a second party with a different party leader. A few hours in, a party member crashed, and then the party leader crashed right after.

Might also be worth noting that I've been reloading a save right outside Helgen (prior to connecting) in order to facilitate new players joining. As a result, some party members occasionally have more progression on their characters, maybe one or two quests max. I think we've been _reasonably_ diligent about not desyncing too far from the party leader's game overall though.

I have tried restarting the server to no avail, as well.

## Steps to reproduce

1. Start the game
2. Load a saved game outside Helgen
3. Connect to a server with multiple players, join a party, begin playing
4. Within an hour or two, someone's game will crash. We've seen the party leader crash as well as party members.

## Reproduction rate

Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
People start crashing an hour or two into the session.

## Expected result

Game should not crash

## Evidence (optional)

Would be very happy to provide logs, we are fairly motivated to play/troubleshoot so I can get logs from multiple systems. Where should I be looking for crash logs?

Thanks for all you do, the mod is amazing! Any troubleshooting tips or useful advice to reduce crashes would be appreciated!

Edit:

Just remembered something else. Probably unrelated but the server says `[error] Sentry init failed` every time it starts up. This doesn't seem to affect anything but I'm not sure what Sentry is.

**Comment by ToeKneeRED** [comment]
Not sure what the overlying issue would be here. However, AES-NI is no longer required as of v1.3.0, and the backpacks being enabled on one very well may be what causes more crashing than usual, the only way to tell would be to delete it and check. Not sure about the technical aspect of the party system but switching party leaders with the same playthrough may cause problems, but not sure if relevant in this case.

**Comment by Necarispox** [comment]
I run the game on windows and have the same problem. The Game crashes very often when we are in the city and manage our Inventory (Open the inventory, crafting table etc) But only i crash. My friend doesnt. We play with the recommended server.

**Comment by RobbeBryssinck** [comment]
Closing this as there are no specific repro steps that cause the crash, and these inventory related crashes have most likely been fixed in 1.4.
