### ISSUE TITLE
How to make the mod support other mods with compilation

### ISSUE THREAD

**Issue by serifas** [tiltedphoques/TiltedEvolution#530]
Hello I am wondering if it is possible to compile the server to support specific mods such as hair styles or body morphs?

**Comment by jgilbrook** [comment]
It sounds like what you're asking for is the enableModCheck, otherwise the server has no bearing on the mods you run.

You can enforce the mod load order within the server config:
https://wiki.tiltedphoques.com/tilted-online/guides/server-guide/server-configuration#benablemodcheck
