### ISSUE TITLE
selecting .exe file isnt working

### ISSUE THREAD

**Issue by Scout191** [tiltedphoques/TiltedEvolution#534]
So i installed skyrim together with vortex and added a tool to the dashboard in vortex selected SkyrimTogether and when i try to launch it, it asks for an SkyrimSE.exe file but when i select the SSE.exe file it says that i dont have the right to open the file, please ask the owner of the file for permissions. Can anyone help?
also i installed skyrim through xbox app if that information helps

**Comment by ToeKneeRED** [comment]
This is meant for bug reports, questions like this should be asked in the questions channel in the [discord](https://discord.gg/skyrimtogether). The mod [does not work on the Xbox Gamepass version of Skyrim Special Edition](https://wiki.tiltedphoques.com/tilted-online/general-information/supported-games).
