### ISSUE TITLE
Random Crashes while entering the inventory or using crafting stations

### ISSUE THREAD

**Issue by Necarispox** [tiltedphoques/TiltedEvolution#535]
Like the Title says. It crashes while entering the inventory or using the crafting stations. But it only happens to the player who is not the Group-leader. We play as a Group of two. Only i, who is not the Group-leader experience these crashes. We are playing while using the uk.playtogether.gg server.

To anybody with the same problem: We work around this problem with me disonnecting from the server, doing all the buying and crafting and then me connecting again. A little bit annoying but better then constant crashings.

**Comment by isaaclw** [comment]
Similar to #520

**Comment by Dragonisser** [comment]
duplicate of #520
