### ISSUE TITLE
STR UI issues with low resolution

### ISSUE THREAD

**Issue by stenliis** [tiltedphoques/TiltedEvolution#540]
## Version of Skyrim Together
v1.3.2 - official build

## Description
Settings UI:
- Scroll bars react on keyboard arrow input and mouse wheel, but clicking and dragging the scroll bar does not work.
- Windows is too narrow, so it displays only the first letter of settings in the dropdown. 
- Opened dropdown have an issue with multi-line values.

![Settings-UI](https://user-images.githubusercontent.com/13061508/206903849-45f06dc3-baf3-474a-84af-5baaf2b07660.png)

![Settings-UI2](https://user-images.githubusercontent.com/13061508/206903859-99b9369e-0511-4f79-9087-9e5891a6d931.png)

Public server listing:
- Scroll bars cannot be dragged.
- Value of server listing is not properly aligned

![Public-server](https://user-images.githubusercontent.com/13061508/206903804-01ce76a5-136f-4d63-872a-527c5e243f30.png)

Chat UI:
- part of connect button is outside of rendered windows, but most noticeable it is after connecting to the server, when button  text change to DISCONNECT.

![Chat-UI](https://user-images.githubusercontent.com/13061508/206903729-3c9bf2b8-d959-4fe8-8e18-c964b2cae21b.png)

Party menu UI:
- party cannot be formed, because part of text and button are rendered outside window. 

![Party-Menu-UI](https://user-images.githubusercontent.com/13061508/206903777-97ef90e8-0635-486d-929c-958b513875d3.png)

## Steps to reproduce
- Run Skyrim Special Edition Luncher
- Set Resolutions to 800x450 (16:9). Note, windowed mode must me enabled to see this resolution on my system.
- Run STR
- load into the game world
- use STR UI

## Reproduction rate
100%

**Comment by Dragonisser** [comment]
Dumb question, but why are you playing in such a resolution? We dont really support such small resolutions.

**Comment by Dragonisser** [comment]
We don't support such small resolutions without a good reason.
