### ISSUE TITLE
STR UI issue with window resize

### ISSUE THREAD

**Issue by stenliis** [tiltedphoques/TiltedEvolution#541]
## Version of Skyrim Together
v1.3.2 - official build

## Description
STR doesn't react correctly on window resize.
When the window is resized to a smaller size, UI is resized as expected.
When the window is resized to bigger size, UI is resized, but part of it is cut out.

![Resized-smaller](https://user-images.githubusercontent.com/13061508/206910046-e2cf8e87-510f-48ac-96ce-637d24a86739.png)

![Resized-bigger](https://user-images.githubusercontent.com/13061508/206910051-d017f5d9-7cbd-409e-b7b6-3d94397c7df6.png)

## Steps to reproduce
- Run Skyrim Special Edition Launcher
- Set Windowed Mode and Resolutions to 1280x720 (16:9), on lower resolution is cut out more apparent.
- Run STR
- load into the game world
- display STR UI
- resize STR window

## Reproduction rate
100%

**Comment by Dragonisser** [comment]
Not intended to be resized.
