### ISSUE TITLE
Camera and animation wigs out if two players mount same horse

### ISSUE THREAD

**Issue by LiamKarlMitchell** [tiltedphoques/TiltedEvolution#545]
## Version of Skyrim Together
v1.3.2

## Description
Two friends in party were able to mount same horse.
One jumped off ok but the others camera was borked.

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, E.g.

1. Start the game and connect etc with a friend.
2. Steal a horse as party leader and mount it.
3. Friend also mounts the horse.
4. Friend seizes control of the horse and steers it around map.
5. Friend fast travels.
6. Friend hops off horse
7. Party leader (first person on horse)  has completely screwed camera.

Can't seem to reset camera with dieing or tc tfc in console.
Can't hop on another horse.

Saving/loading/Restarting game does not fix it.

## Reproduction rate

Please check just _one_ of the following reproduction rates:
Have seen it happen just the once have not attempted reproduction yet.
- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Either two players can ride the same horse and there is no issue or only allow 1 person on a mount.

## Evidence (optional)

Show us what happened.

Whilst riding the horse we had different views.
![image](https://user-images.githubusercontent.com/1968109/208334350-f6dd5ed1-d835-4f70-98c5-255f7d20fffb.png)
![image](https://user-images.githubusercontent.com/1968109/208334364-29f204c6-3efd-498a-bc46-03a285de6ce7.png)

My camera at one point was detatched from camera controls but I could walk around the camera did not change angles until it went to a new camera point/scene?

After attempting some things like dieing a few times/save/load.
My character is on left trying I tried to get the guard to kill me I can't get the camera back on the character :(.
![image](https://user-images.githubusercontent.com/1968109/208334424-8b447e54-2861-46c9-92d2-807681e0f3f2.png)

**Comment by Dragonisser** [comment]
Or you could just not ride a horse when someone else does.

**Comment by RobbeBryssinck** [comment]
Double horses is a feature, not a bug. Of course, it is buggy, but if that's an issue, just don't double mount a horse.
