### ISSUE TITLE
Almost instant recovery of player HP/MP/SP 

### ISSUE THREAD

**Issue by stenliis** [tiltedphoques/TiltedEvolution#546]
## Version of Skyrim Together
v1.3.2 - official build

## Description
STR does not currently support Wait for time progression, but players can still display Wait menu pressing T and attempt advance time.
This attempt leads to small stutter, time does not change and player HP/MP/SP are recovered to 100%.

This is an issue mainly for PVP, because PVP is not recognised as combat, so player can abuse Wait without limitation.

NOTE: It seems that attempt to wait when player is running do not recover SP, but HP/MP are still recovering to 100%.

## Steps to reproduce
- PVP enabled server
- Player A running arround, casting spells, getting hits from other players
- Player A have low HP/MP/SP
- Player A click T, click Enter
- Player A have HP/MP/SP recovered to 100%

## Reproduction rate
100%

## Expected result
There are two possible fixes
- PVP is correctly recognised as combat => player can not Wait during PVP
- Proper implementation of Wait/Sleep => player can Wait only when every player confirms it => not viable in PVP

**Comment by RobbeBryssinck** [comment]
PvP is not supported by us. The intended use of the mod is co-op, and therefore, any PvP issues fall outside of the scope of development.
