### ISSUE TITLE
Overpowered stealth in PVP

### ISSUE THREAD

**Issue by stenliis** [tiltedphoques/TiltedEvolution#547]
## Version of Skyrim Together
v1.3.2 - official build

## Description
A player can not detect the other player sneaking around.
This means that sneaking player always deal bonus damage for sneak attack in PVP.

![StealthPVP](https://user-images.githubusercontent.com/13061508/209327866-5a276abb-2998-44cd-900d-dd43947551a5.png)

## Steps to reproduce
- PVP enabled server
- Distance between player A and player B is 1 meter
- Player A starts sneaking and use the bow to headshot player B
- Player A sees that attack dealt bonus damage

NOTE: work also for melee attacks

## Reproduction rate
100%

## Expected result
I don't think there is a good way how to integrate Skyrim stealth system into PVP.
So I think there only these ways how to resolve this issue:
- Completely disable sneak bonus damage in PVP
- Deal sneak bonus damage only when the player is sneaking and also using some form of invisibility

**Comment by RobbeBryssinck** [comment]
PvP is not supported by us. The intended use of the mod is co-op, and therefore, any PvP issues fall outside of the scope of development.
