### ISSUE TITLE
Crash when teleport to player which uses Arcane Enchanter

### ISSUE THREAD

**Issue by stenliis** [tiltedphoques/TiltedEvolution#549]
## Version of Skyrim Together
v1.3.2 - official build

## Description
Using party menu teleport to another player, which uses Arcane Enchanter lead to his crash.

## Steps to reproduce
- Player A and B (both players use the same savefile), join a local server in Whiterun near priest of Talos (Heimskr)  
- Player A create a party and invite player B
- Player B joins the party
- Player B runs and enter Dragonsreach
- Player B uses Arcane Enchaner next to Farengar Secret-Fire
- Player A use party teleport to player B
- Player B may crash
- If player B doesn't crash, player A should leave Dragonsreach ASAP and teleport to player B ASAP after loading to Whiterun, if this fails crash player B, try to repeat again.

NOTE: In my testing It did not require more than 3 attempts to crash player B with this method, but most common is one retry.
NOTE: Server and both players run on the same PC.
NOTE: I am pretty sure, this crash can be caused by other way, but this one is the only reliable way that I found.

BT from v1.3.2 - official build
[arcane-crash-bt.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10297188/arcane-crash-bt.txt)

## Reproduction rate
100%
NOTE: It seems to me like Data Race which mean that ability reproduce the issue on other system may vary. 

## Expected result
Not crashing.

## Debuging on dev branch.
I have seen multiple backtrace that point to Code/client/Games/Skyrim/ExtraData/ExtraDataList.cpp  ExtraDataList::Contains(...), specifically when working with bitfield->data[index].
The value of the index is valid (smaller than 0x18), so adding check does not solve this.  
Adding BSScopedLock<BSRecursiveLock> directly into ExtraDataList::Contains(...) did not fix the issue.
It seems to me that this part of memory is released by another thread.

In my extended logs I can see:
"Remove entity that contain Actor XXX with server id YYY" -- my custom log added after m_world.remove<LocalAnimationComponent, LocalComponent>(entity);
"Relinquished control of Actor XXX with server id YYY"
"Setting inventory for Actor XXX"

![crash4](https://user-images.githubusercontent.com/13061508/209402240-3e83d356-6dc1-4636-ad8b-216fe01bb5dd.png)

In CharacterService::OnNotifyRelinquishControl() is m_world.remove<LocalAnimationComponent, LocalComponent>(entity);
I suspect this line lead to release of memory that is accessed by different thread in ExtraDataList::Contains(...).

**Comment by RobbeBryssinck** [comment]
We don't free ExtraDataList, we let the game handle that. Your suspicion is probably correct, however. The game seems to free instances of ExtraDataList on non-main game threads, which is quite annoying, since locking it from our side would happen too late, as the list would alraedy be deallocated.

Do you gave a fuller call stack for the Contains() crash?

**Comment by Luc45** [comment]
Same behavior. When my brother is using the Archane Enchanter and I teleport to him, he crashes.

**Comment by stenliis** [comment]
I managed to reproduce the crash and produce BT on the dev branch(commit c359d5c006d127bec5b3f0b7ce758ba90f2877c1).

When I tried using the dev branch with commit f8a4d5ae69eb9f0a824f987eb3c647e3c0c145f9 (PR #552 Fix: equipment related crash), I could not reproduce crash using the same steps.
But I can produce another crash, when after few leave->teleport cycle party leader click disconnect, this sometime result in crash of party leader.

The crash caused by disconnect is present on current dev (126ff69f771612711287b77eba764e3f928b295f) too.

It looks to me that this issue was resolved by PR #552 and crash during disconnect is a separate issue, but I not 100% sure of it.
[c359d5c006d127bec5b3f0b7ce758ba90f2877c1-crash.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10472890/c359d5c006d127bec5b3f0b7ce758ba90f2877c1-crash.txt)
[c359d5c006d127bec5b3f0b7ce758ba90f2877c1-crash2.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10472891/c359d5c006d127bec5b3f0b7ce758ba90f2877c1-crash2.txt)
[f8a4d5ae69eb9f0a824f987eb3c647e3c0c145f9-crash-disconnect.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10472892/f8a4d5ae69eb9f0a824f987eb3c647e3c0c145f9-crash-disconnect.txt)
[f8a4d5ae69eb9f0a824f987eb3c647e3c0c145f9-crash-disconnect2.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10472893/f8a4d5ae69eb9f0a824f987eb3c647e3c0c145f9-crash-disconnect2.txt)
[126ff69f771612711287b77eba764e3f928b295f-crash-disconnect.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10472894/126ff69f771612711287b77eba764e3f928b295f-crash-disconnect.txt)
[126ff69f771612711287b77eba764e3f928b295f-crash-disconnect2.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10472895/126ff69f771612711287b77eba764e3f928b295f-crash-disconnect2.txt)
[5160db2700464c736be14bb85db1ff35a682b579-crash.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10472896/5160db2700464c736be14bb85db1ff35a682b579-crash.txt)
[5160db2700464c736be14bb85db1ff35a682b579-crash-disconect.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10472897/5160db2700464c736be14bb85db1ff35a682b579-crash-disconect.txt)
[5160db2700464c736be14bb85db1ff35a682b579-crash-disconect2.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10472898/5160db2700464c736be14bb85db1ff35a682b579-crash-disconect2.txt)

**Comment by stenliis** [comment]
Crash on disconnect almost certainly unrelated => closing issue.
