### ISSUE TITLE
Player character face skin color turns white on loading screen

### ISSUE THREAD

**Issue by Erithionis** [tiltedphoques/TiltedEvolution#558]
## Version of Skyrim Together

v1.3.2

## Description

The face color of the player appears to change to white skin once the player goes through a loading screen for the first time. inputting 'showracemenu' into the console fixes this permanently it seems

## How to reproduce this issue.

Create New Save Game or open the console & input 'coc riverwood'
Create a character with the darkest skin possible (to best show the effects of the bug)
Go through a loading screen (such as into the Riverwood Trader)
Go into third person & look at the player character's face, it should now be white.

### Optionally:
Open the console & input 'showracemenu'
Ensure your character's face's skin color is back to what you initially set it as
Finish your character again & go through another loading screen
Your character's face's skin color should remain the color you set it as

## Reproduction rate

   [X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (every time)
   Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
   Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

The skin color of the player character's face remains the same as what was chosen in character creation

## Evidence
![20230105221824_1](https://user-images.githubusercontent.com/47090671/210944400-5418731e-debf-4342-8e40-c83dd61e2f64.jpg)
Above: Orc player with no mods except Skyrim Together experiencing the white face bug
Below: Nord player with mods, including the Face Discoloration Fix mod, experiencing the white face bug
![20230105225657_1](https://user-images.githubusercontent.com/47090671/210947483-cee45fff-28e2-45e1-a9ac-63c59ee55dc3.jpg)

**Comment by Dragonisser** [comment]
Don't use COC. Thats exactly why this happens.
