### ISSUE TITLE
Emerald dragon claw door crashes the game.

### ISSUE THREAD

**Issue by wolfofwierdness** [tiltedphoques/TiltedEvolution#561]
# READ IF YOU HAVE MODS

Tested with just STR

## Version of Skyrim Together

1.3.2

## Description

The emerald dragon claw door in Reachwater Rock crashes the game

## Steps to reproduce

1. Start the game.
2. Load or start a game.
3. Go to Reachwater Rock.
4. Pick up the emerald dragon claw.
5. Match the symbols on the dragon puzzle door to the dragon claw.
6. I recommend quicksaving at this point, though not necessary.
7. Use the claw to open the door
8. Crash to desktop

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Expected result for the game is the door to open and I'm able to proceed.  But it crashes.

*Edit: Changed "green" to "emerald", due to proper name.

**Comment by stenliis** [comment]
Managed reproduce issue, bt from dev branch based on eb51951d7b7e8aed6afa35fd4cdab80a98d49bbd
[emerald-claw-crash-on-keyhole-activate.txt](https://github.com/tiltedphoques/TiltedEvolution/files/10561405/emerald-claw-crash-on-keyhole-activate.txt)

**Comment by xForcer** [comment]
@wolfofwierdness Can you test again in the latest version and see if it's fine now? We can then close this issue

**Comment by wolfofwierdness** [comment]
I just went through the process of updating.  Went and checked with a fresh character after verifying that it was installed right, the door appears to function correctly now.
