### ISSUE TITLE
Can we merge "dev" branch?

### ISSUE THREAD

**Issue by Luc45** [tiltedphoques/TiltedEvolution#567]
Hi, thank you for creating this amazing mod.

I was wondering if it's possible to release the [dev](https://github.com/tiltedphoques/TiltedEvolution/tree/dev) branch as a new version, specifically because of two commits (link: [1](https://github.com/tiltedphoques/TiltedEvolution/commit/5d075ca674c5c380b6097aded831a16303118f13) and [2](https://github.com/tiltedphoques/TiltedEvolution/pull/559)) that I believe will improve the mod's stability.

Thank you for your time and consideration.

Now, a poem by ChatGPT:

> A mod so great, oh what a feat,
> It brings joy and wonder, can't be beat.
> 
> But there's a branch, dev, you see,
> With changes that would set us free.
> 
> Two commits, links one and two,
> Stability they promise to imbue.
> 
> So I ask, oh great creator,
> Is it possible to make it later?
> 
> A release, with dev's updates bright,
> To bring even more delight.
> 
> Thank you for your time, we say,
> And for this amazing mod, each day.

**Comment by RobbeBryssinck** [comment]
You can always try building it yourself, it's not too difficult: https://wiki.tiltedphoques.com/tilted-online/technical-documentation/build-guide

Though a new version should be coming soon.
