### ISSUE TITLE
The game crashes when trying to join any server

### ISSUE THREAD

**Issue by ykbtss** [tiltedphoques/TiltedEvolution#583]
The game crashes when trying to join any server (no creation club mods). In previous versions, the problem was in the AES instructions, but after this was fixed, however, the crashes remained. Help please.
[SkyrimTogether.exe.7312.zip](https://github.com/tiltedphoques/TiltedEvolution/files/11023769/SkyrimTogether.exe.7312.zip)

**Comment by Dragonisser** [comment]
Use the template
