### ISSUE TITLE
/SetTime Crashes the Server with any value on 1.5.0

### ISSUE THREAD

**Issue by Cyphs** [tiltedphoques/TiltedEvolution#587]
## Version of Skyrim Together

v1.5.0

## Description

Using any value for setting the time such as `/SetTime 12 00` crashes the SkyrimTogetherServer on Windows 10, 11, and Docker.
On Docker, there is also the following error:
>`terminate called after throwing an instance of 'std::bad_any_cast'`
`  what():  bad any_cast`

## Steps to reproduce

Enter any value to set the time on the server with `/SetTime HH MM`.

## Reproduction rate

- [X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)

## Evidence (optional)

It does not occur on v1.4.1 but has started occurring on v1.5.0

**Comment by TJHeeringa** [comment]
Has been fixed in [this](https://github.com/tiltedphoques/TiltedEvolution/pull/588) pull request.
