### ISSUE TITLE
Combat - Target prioritization

### ISSUE THREAD

**Issue by xForcer** [tiltedphoques/TiltedEvolution#591]
## Description

After combat aggro issue has been resolved and it's now using SetTargetEx function instead of re-initializing Combat, we should expand upon the existing logic. 
Current system will almost always target party leader and only way for remote players (party members) to change aggro is to hit an actor (Enemy NPC).

Proposition:
- Implement modern RPG PvE aggro features such as tanking, enemies going for a weak target, damage dealer... Cooldowns between changing targets should still remain (existing cooldown is 5 seconds). Some situations in combat could cancel that cooldown and immediately change the target, since 5 seconds is a lot in a fast paced high damage combat, just keep in mind NOT to cancel cooldowns too much since that will make the game easier!

**Comment by DJLegends1011** [comment]
+1!!!!

**Comment by xenonbart** [comment]
I second this, the AI targeting the party leader first is very annoying as they run past any party member just to get to the leader which makes the AI seem very dumb because they ignore a direct threat in front of them.

**Comment by Dragonisser** [comment]
This is an ongoing issue that we are working on. 1.6.1 finally fixes this and makes combat a lot more enjoyable and how its supposed to be.

Background:
For some reason, remote players were set to the status "fleeing" hence why the AI were ignoring them and focusing on the host.
