### ISSUE TITLE
Vampire player quest not fired correctly when PC becomes vampire

### ISSUE THREAD

**Issue by DJLegends1011** [tiltedphoques/TiltedEvolution#596]
## Version

v1.5.0 Dev Release

## Description

When beta testing the dev build of skyrim together we decided to see how vampires would work. we first went inside a random vampire cave and took turns getting drain till we got the disease I however decided to precede to leave server wait 3 local days and reconnect while he stayed inside server the results were:
when looking at eyes which were supposed to be vampiric they were default and same with skin **however** the spells did sync correctly though yet when checking if player is vampire it still shows as vanilla race

## Steps to reproduce

1. Start the game.
2. load save and head near nearest vampire cave
3. Connect to the server.
4. stand patiently till you have become infected
5. wait 3 ingame days or disconnect and wait 3 local days 
6. reconnect and see unintended results

## Reproduction rate

- [ ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)

## Expected result

player should turn into vampire and remote player should see the effects of it happeneing

## Evidence (optional)

will provide photos later

**Comment by Dragonisser** [comment]
You left the server which means you didn't follow the playguide.

**Comment by DJLegends1011** [comment]
I literally tested this with latest version of str dev release and with cosi guideline no mods
and for god sakes i never left one of the moderator kicked me and if you wanna see if this bug is reproducible please test it yourself
