### ISSUE TITLE
Vilkas's training - never ends combat.

### ISSUE THREAD

**Issue by JHstrutton2000** [tiltedphoques/TiltedEvolution#598]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.
None.

## Version of Skyrim Together
v1.5.0

*For example:*

v1.1.0

## Description

A clear and concise description of what the bug is, Include any formIDs relevant for us to use E.g.,
When connected to a server and starting vilkas's training, it never ends. when I force the battle to end by typing the command stopcombat and then the training ends.

Related formIDs|
---------------|
[Flames - 12FCD](http://en.uesp.net/wiki/Skyrim:Flames)|
[Nazeem - 1A6A4](http://en.uesp.net/wiki/Skyrim:Nazeem)|

## Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, E.g.

1. Start the game.
2. Connect to the server.
3. Load a saved game and start the companions quest line.
4. start the training, and hit him a few times and it should end. which it does not do.

## Reproduction rate

Please check just _one_ of the following reproduction rates:

- [x ] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Describe your expected result i.e. answer the question "What did you expect would happen?"
Release a patch that places a script on vilkas and stops combat at the expected time. That would fix the problem, I would write it myself if I knew how to write skyrim mods.

## Evidence (optional)

Show us what happened.

**Comment by DJLegends1011** [comment]
had this same issue will need to fix the script to detect both players
