### ISSUE TITLE
Constant crashing, mostly in Whiterun.

### ISSUE THREAD

**Issue by Slayer5934** [tiltedphoques/TiltedEvolution#599]
# READ IF YOU HAVE MODS

**Note**: If you have mods installed, DO NOT submit a bug report. The chances of one of these mods causing the issue is very high, and so, such bug reports are worthless to us.

## Version of Skyrim Together

1.5.0

## Description

Randomly the game crashes, pretty rarely before Whiterun, very commonly in Whiterun. This is with just me and one other person.

## Steps to reproduce

1. Start the game.
2. Create new save.
3. Complete Helgen escape.
4. Connect both players to server. (I have tried changing which PC hosts the server also via ethernet and wireless.)
5. Create party and invite other player. (I have tried host party leader and non-host party leader as well.)
6. Play all the way up to Whiterun, only crashed once before reaching Whiterun, it crashes every time both before and after receiving the claw quest randomly while making our way out; We have *never* been able to get past this,

## Reproduction rate

- [X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)
- [ ] Occasional: I can reproduce this bug by following the steps to reproduce around 50% of the time
- [ ] Rare: I can reproduce this bug by following the steps to reproduce around 10% or less of the time

## Expected result

Not crash, or atleast not every single time.

## Evidence (optional)

These are from the last crash, we had talked to Balgruuf and received the quest for the claw, went through the door out, and were on our way out of Whiterun.
[cef_debug.log](https://github.com/tiltedphoques/TiltedEvolution/files/11644375/cef_debug.log)
[tp_client.log](https://github.com/tiltedphoques/TiltedEvolution/files/11644376/tp_client.log)

**Comment by Slayer5934** [comment]
I have tried Nucleus Coop and the crashes are wayyyy more rare now, and even more rare after disabling Windows Defender, I don't know how that would help the developers but for anyone that sees this maybe disable Defender while playing atleast and try Nucleus Coop if your PC is powerful enough (you can even put players on different screens.)

**Comment by ToeKneeRED** [comment]
To make sure, no other mods besides STR and the address library? Also, have all players deleted/disabled the included cc content?

**Comment by Slayer5934** [comment]
> To make sure, no other mods besides STR and the address library? Also, have all players deleted/disabled the included cc content?

Yes, I followed the install guide exactly on both computers making sure to delete cc, I will admit the first time i played with cc just to see if it would crash; However after I tried and it crashed I completely removed the Skyrim documents and steam/common folders and followed the guide more exactly. These computers are side by side connected to the router via ethernet.

I do think it's possible that all the issues were somehow caused by Windows Defender, as disabling it has resulted in 0 crashes (other than my partner crashing it one time by accident by going into the next cell at the same time as me instead of waiting.)

**Comment by Slayer5934** [comment]
I will open this again if I ever can figure out what was causing it.
