### ISSUE TITLE
My whole pc is fucked

### ISSUE THREAD

**Issue by TheZombieStriker** [tiltedphoques/TiltedEvolution#607]
Version of Skyrim Together: can't check version but it's whatever is listed for the mod manager download as of 7/5/2023

<!--
A clear and concise description of what the bug is, Include any formIDs relevant for us to use E.g.,

-I don't know what a form id is. I was playing the game with a friend after refollowing the guide since we were unable to get the menu open (forgot to make custom launch path). We had made it to bleak falls barrow and we decided to stop for a second so I could go and eat. After I came back the pc went to sleep, when turned on all the previously opened programs were closed and when reopened, the pc crashed. I can now no longer open anything or be on the pc for longer than 1-2 minutes without crashing. I don't know what happened while I was gone, nor can I recreate it (for obvious reasons). It's a desktop, from the top of my head I can remember it had an amd rtx590 for the graphics card, I can't remember the cpu, it was all installed to a secondary "D" drive. The pc ran fine running base skyrim, death stranding, son's of the forest. I doubt you can fix this or hell even recreate it, just thought I'd let you know since nothing else has been done with the pc since it working perfectly fine and being completely unusable.

Related formIDs|
---------------|

Steps to reproduce

How to reproduce this issue. Be as specific as possible and try to only include instructions you believe are necessary to reproduce said issue, E.g.

-I doubt you'd want to recreate it but here's what we did in as much detail as possible

1. Start game
2. load save files made the night before (within the custom launch option)
3. run server using use.playtogether.gg
4. connect
5. friend connects
6. go to riverwood
7. stole ingots
8. went to cabin, stole everything
9. Go to bleak falls barrow
10. kill the guy who was trapped and had the golden claw
11. take claw
12. walk back to the round room
13. leave characters there
14. come back 10-20 minutes later

Reproduction Rate: undeterminable

<!---
Expected result:

Describe your expected result i.e. answer the question "What did you expect would happen?"

-The game would be open, or the pc would work

Evidence (optional)

-I'm unable to put any form of image or the sorts in

**Comment by TheZombieStriker** [comment]
Fuck it, it won't show the whole thing, just delete this as it won't let me

**Comment by lfkdev** [comment]
?
