### ISSUE TITLE
Complete Quest Sync between party leader & members

### ISSUE THREAD

**Issue by Jacobwasbeast** [tiltedphoques/TiltedEvolution#608]
## Description

I want a feature where if I join a party I want all the quest's objectives, and stages to be synced so party members don't have bugged out quests.

## Additional context

Sometimes the game crashes and I have to rejoin the party from a later save which causes my client to bug out and display previous objectives and quests that have already been completed in the party, for context I crashed when my friend, the party leader, completed a Dawnguard quest and when I rejoined the party after rejoining the server I still had the previous quest.

**Comment by SatinCake** [comment]
+1

**Comment by Dragonisser** [comment]
This wont work. There is a reason we explicitly state that you have to play together and never stray away from each other in waht you do and what quests you do.
