### ISSUE TITLE
Version mismatch: Please do not check commit hash

### ISSUE THREAD

**Issue by ALiwoto** [tiltedphoques/TiltedEvolution#620]
## Description

My server version is only 1 commit ahead of my client, but it's denying my connection because the commit hash doesn't match [here](https://github.com/tiltedphoques/TiltedEvolution/blob/5849b46f707f900ec4261acf7b283ef5a7373376/Code/server/GameServer.cpp#L710C44-L710C44).
If possible, please ignore the commit hash in version when matching it on server-side, or add a variable such as `EnableVersionMatch` on server side.

## Additional context

![image](https://github.com/tiltedphoques/TiltedEvolution/assets/70187458/d82b2c8c-5583-4130-9c06-c0500aa02020)

**Comment by Dragonisser** [comment]
Why is your version one commit behind?
