### ISSUE TITLE
When player is freezing and they die, they'll keep dying forever

### ISSUE THREAD

**Issue by ALiwoto** [tiltedphoques/TiltedEvolution#621]
The mechanism to "spawn player nearby after death" will cause the player to die again due to coldness being applied on them, so they'll just keep dying forever in the same place.

**Comment by VENDETTA5** [comment]
> The mechanism to "spawn player nearby after death" will cause the player to die again due to coldness being applied on them, so they'll just keep dying forever in the same place.

Coldness? Dude, Survival mode is completely broken on Together(Because the time doesn't pass when you sleep). Use Survival Mode Prompt Removed mod to get rid of it forever.

**Comment by ALiwoto** [comment]
> > The mechanism to "spawn player nearby after death" will cause the player to die again due to coldness being applied on them, so they'll just keep dying forever in the same place.
> 
> Coldness? Dude, Survival mode is completely broken on Together(Because the time doesn't pass when you sleep). Use Survival Mode Prompt Removed mod to get rid of it forever.

I see, well this wasn't mentioned in wiki lol, thanks for mentioning it.

**Comment by Dragonisser** [comment]
1. Use the template
2. It is mentioned several times to remove ANY CC mods that Skyrim Special Edition comes with and to not use mods in general.

https://wiki.tiltedphoques.com/tilted-online/general-information/faq#q-can-i-use-other-mods-with-this-mod
https://wiki.tiltedphoques.com/tilted-online/guides/client-setup/using-modorganizer2-mo2/disabling-the-anniversary-editions-included-creation-club-content
https://wiki.tiltedphoques.com/tilted-online/guides/troubleshooting/disabling-the-anniversary-editions-creation-club-content
https://wiki.tiltedphoques.com/tilted-online/guides/troubleshooting/disabling-the-anniversary-editions-creation-club-content/using-vortex-mod-manager#removing-the-creation-club-content
