### ISSUE TITLE
Updating the docker image on linux using the "Latest" tag downloads an older version

### ISSUE THREAD

**Issue by arbitercay** [tiltedphoques/TiltedEvolution#623]
## Version of Skyrim Together

v.1.5.0 (from v1.3.2)

## Description

Whenever I have to update my skyrim server on Linux and I use the "Latest" tag, it always downloads version 1.3.2 of the docker image. I have to specify "amd64-1.5.0" when I want to download the latest image from docker.

I have to modify the end of the command to specify the version I want to download:

docker run -d -it --name skyrimserver ........... tiltedphoques/st-reborn-server:amd64-1.5.0

## Steps to reproduce

I used this set of commands from the server setup guide, running "apt update" beforehand, and v1.3.2 is downloaded.

docker run -d -it --name skyrimserver -p 10578:10578/udp -v /opt/docker/skyrimserver/config:/home/server/config -v /opt/docker/skyrimserver/Data:/home/server/Data -v /opt/docker/skyrimserver/logs:/home/server/logs tiltedphoques/st-reborn-server:latest

## Expected result

My goal is to run a weekly cron job on my server to kill the server, delete the docker image, download the latest docker image and start the server. This is what the script looks like:

#!/bin/bash
docker stop skyrimserver -t 1
docker rm skyrimserver
docker run -d -it --name skyrimserver -p 10578:10578/udp -v /opt/docker/skyrimserver/config:/home/server/config -v /opt/docker/skyrimserver/Data:/home/server/Data -v /opt/docker/skyrimserver/logs:/home/server/logs tiltedphoques/st-reborn-server:amd64-1.5.0
docker start skyrimserver

I'd like this script to not download a specific docker image, but to instead always get the latest version so that I can let my server keep itself perpetually updated on it's own. My server is also always on and public, so I'd like to occasionally reset it each week so that new players/parties don't have broken quests because a particular party leader isn't online (my current script should accomplish this already). I could be missing something with regards to how docker works in general, but any assistance would be appreciated.

**Comment by Dragonisser** [comment]
![image](https://github.com/tiltedphoques/TiltedEvolution/assets/4233773/a5997a9f-ac2f-439d-8c51-7080b4a6b698)

Worked perfectly fine.
