### ISSUE TITLE
Small Documentation issue on wiki, from change in Vortex Ui

### ISSUE THREAD

**Issue by LeoStaley** [tiltedphoques/TiltedEvolution#625]
On The wiki page, [Making a custom launch option in VMM](https://wiki.tiltedphoques.com/tilted-online/guides/client-setup/using-vortex-mod-manager-vmm/skyrim-together-reborn/making-a-custom-launch-option-in-vmm), Step 3 says, 

> 3. Press the Add Tool button and then New

Unfortunately, recent changes to the VMM UI have removed the text that says "Add Tool" and replaced it with just a big button with a + sign on it. **AND you can't even see it without scrolling within the "tools" dashlet!** 

I spent 20 minutes trying to figure out how to follow the instructions in both the Youtube tutorial AND the Wiki instructions because Vortext made this (outrageously stupid) change. 

Please update the Wiki tutorial and the Youtube tutorial to more precisely guide users on how to do this step. 

(sorry if this is mislabeled as a bug, but I didn't know where else to submit the request.)

**Comment by Dragonisser** [comment]
https://github.com/tiltedphoques/gitbook-wiki/pull/27
