### ISSUE TITLE
[Feat Req] Add Chest sync config in STServer.ini

### ISSUE THREAD

**Issue by wonson** [tiltedphoques/TiltedEvolution#629]
## Description

I understand currently there is a complicated Chest share mechanism in Skyrim Together Reborn.

However, I think a simple mechanism like the current unsync body loot and home chest is good too.

I hope there is an option that we can choose what we want.

## Additional context

I played with my family at a LAN server we set.
I run a dungeon at the night before, and loot everything because I did not know yet. 

When I played with her today and she saw every chest is empty, she was so frustrated.

We do want to fight alongside each others, and explore the same world together. But we want our loot as well.

I hope there is an option so that we have freedom to choose.

**Comment by wonson** [comment]
https://github.com/tiltedphoques/TiltedEvolution/blob/c8e71333798741f31bc9fcb302887b3eb984155e/Code/client/Services/Generic/ObjectService.cpp#L70
```
bool ShouldSyncObject(const TESObjectREFR* apObject) noexcept
{
    if (!apObject)
        return false;

    switch (apObject->formID)
    {
        // Don't sync the chest in the "Diplomatic Immunity" quest
    case 0x39CF1: return false;
    default: { 
        if (!World::Get().GetServerSettings().SyncChests && apObject.baseForm.formType == FormType::Container) return false; 
        return true;
    }
    }
}
```

I guess this should do the trick?

**Comment by VENDETTA5** [comment]
Welp, actually if she was leading the party all the loot would respawn, lol.

**Comment by VENDETTA5** [comment]
Welp the way the game works, is the person who first enter the dungeon, hosts it. That's why the devs always ask the party host to get into the dungeon first.

**Comment by Dragonisser** [comment]
Follow the gameplay guide.

**Comment by wonson** [comment]
But how about the "Skyrim" chest? Like the tower in the world map?

**Comment by Dragonisser** [comment]
> @VENDETTA5 @Dragonisser
> 
> But how about the "Skyrim" chest? Like the tower in the world map?

The thing is, the gameplay guide clearly states to not play alone on your save. This is what you've done and therefore made your world and your family ones out of sync. 

This is basically defeating the purpose of the mod.

**Comment by wonson** [comment]
Never mind. I build my fork then :)
