### ISSUE TITLE
Impossible to connect to any server on game version 1.6.1170.

### ISSUE THREAD

**Issue by VENDETTA5** [tiltedphoques/TiltedEvolution#637]
## EDIT
Fixed the issue, my installation was messed up.
I would keep this issue still visible for the people like me.

## Version of Skyrim Together
1.5.0

## Description
I just updated my game from version 1.6.1130 to 1.6.1170 and got quite confused when trying to connect to a server I immediately got disconnected, it really doesn't matter which server, and right before I updated  it worked alright.

What's even more confusing the other guy I know seems to have his game work right on the latest version.
## Steps to reproduce

1. Start the game(Console will flash for a second and then vanish, first I was even happy about it).
2. Load a saved game.
3. Connect to the server.
4.Get Super Confused.

## Reproduction rate
- [X] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)

## Load Order
```
  0  0     Skyrim.esm
  1  1     Update.esm
  2  2     Dawnguard.esm
  3  3     HearthFires.esm
  4  4     Dragonborn.esm
  5  5     ccASVSSE001-ALMSIVI.esm
  6  6     ccBGSSSE001-Fish.esm
254 FE   0 ccQDRSSE001-SurvivalMode.esl
254 FE   1 ccBGSSSE037-Curios.esl
254 FE   2 ccBGSSSE008-Wraithguard.esl
  7  7     ccBGSSSE025-AdvDSGS.esm
254 FE   3 _ResourcePack.esl
  8  8     SkyrimTogether.esp
```

## Expected result
Address the issue. I know it's a pain in the butt, but still.

If it's problematic to reproduce I still got backup of my previous game installation.

## Gallery
![image](https://github.com/tiltedphoques/TiltedEvolution/assets/58639745/6f4ba7d4-c383-424f-a95d-7b63ab425ea0)

**Comment by Dragonisser** [comment]
Why do you even have the CC mods installed.
