### ISSUE TITLE
Double Damage on magical attacks if you are not the party leader.

### ISSUE THREAD

**Issue by gamerZ1690** [tiltedphoques/TiltedEvolution#679]
## Version of Skyrim Together

v1.6.5

## Description

Damaging magical attacks deal double damage if you are not the party leader with the exception being concentration based spells like Flames AFAIK.
Enchantments, Shouts, or any spells like Firebolt or Fireball all deal double damage when you are not the party leader.
## Steps to reproduce

1. Start the game.
2. Load a saved game.
3. Connect to the server.
4. Enter a party not as the leader
5. Use any magical attack that's not like focused based like Flames at an enemy.
6. Record the amount of hits it takes to kill an enemy or use a mod that shows damage numbers.

## Reproduction rate

- [x] Consistent: I can reproduce this bug by following the steps to reproduce 100% of the time (*every time*)

## Expected result
Should only deal normal damage

**Comment by RobbeBryssinck** [comment]
Fixed in 1.6.7
