### ISSUE TITLE
Working with the database

### ISSUE THREAD

**Issue by Monax661** [tiltedphoques/TiltedEvolution#686]
Good afternoon, please tell me is it possible to connect a database to the server somehow? We just want to launch a server in Skyrim like an arena, where we can find out who is currently the champion of the arena, as well as introduce the ability to save data on the player's location, so that inventory and location are saved during departure.

**Comment by Dragonisser** [comment]
Just use the server side scripting.
https://wiki.tiltedphoques.com/tilted-online/guides/scripting
